#!/bin/bash


declare -A Self=( 
    [dir]=$(dirname `realpath $0`)
    [lib]=$(dirname `realpath $0`)/lib
    [bin]=$(dirname `realpath $0`)/bin
    [conf]=$(dirname `realpath $0`)/conf
    [exe]=$(basename `realpath $0`)
)

declare -A Ghri=(
    [exe]="${Self[bin]}/ghri.sh"
    [conf]="${Self[conf]}/pkgs.lst"
    [dist]="$HOME/.local/lib/ghri"
    [inst]="$HOME/.local/bin"
)

echo "Installing apps from github...."
echo " >> ${Ghri[exe]} -l ${Ghri[conf]} -d ${Ghri[dist]} -b ${Ghri[inst]} -I"
${Ghri[exe]} -l ${Ghri[conf]} -d ${Ghri[dist]} -b ${Ghri[inst]} -I

