<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="iggu.20190619190259.1"><vh>@settings</vh>
<v t="iggu.20201225013435.1"><vh>@data import-and-init-leo-py-libs</vh></v>
<v t="iggu.20220327131002.1"><vh>@data free-layout-layout</vh></v>
<v t="iggu.20201219000309.1"><vh>Environment</vh>
<v t="iggu.20201219000321.1"><vh>@bool collapse-nodes-during-finds = False</vh></v>
</v>
<v t="iggu.20191204061052.1"><vh>Paths</vh>
<v t="iggu.20191204061525.1"><vh>@string confg-lib-dir = ~/.leo/lib</vh></v>
</v>
<v t="iggu.20191119121604.1"><vh>@commands</vh>
<v t="iggu.20201225013248.1"><vh>@command wip-toggle @key=Alt-w</vh>
<v t="iggu.20201225013248.2"><vh>&lt;&lt; load and import &gt;&gt;</vh></v>
</v>
<v t="iggu.20201225013512.1"><vh>@command wip-remove</vh>
<v t="iggu.20201225013248.2"></v>
</v>
<v t="iggu.20201225013523.1"><vh>@command wip-add</vh>
<v t="iggu.20201225013248.2"></v>
</v>
<v t="iggu.20191119114314.1"><vh>@command rstrip-node</vh></v>
<v t="iggu.20191127153547.1"><vh>@@command create-html-filenode</vh></v>
</v>
<v t="iggu.20191119114302.1"><vh>@buttons</vh></v>
<v t="iggu.20190920201307.1"><vh>@menus</vh>
<v t="iggu.20190920201307.2"><vh>@menu File</vh>
<v t="iggu.20190920201307.3"><vh>@item &amp;close-window</vh></v>
<v t="iggu.20190920201307.4"><vh>@item &amp;file-open-by-name</vh></v>
<v t="iggu.20190920201307.5"><vh>@item &amp;new</vh></v>
<v t="iggu.20190920201307.6"><vh>@item &amp;open-outline</vh></v>
<v t="iggu.20190920201307.7"><vh>@item -</vh></v>
<v t="iggu.20190920201307.8"><vh>@menu Open &amp;With</vh></v>
<v t="iggu.20190920201307.9"><vh>@menu Open Specific &amp;Leo File</vh>
<v t="iggu.20190920201307.10"><vh>@item open-cheat-sheet-leo</vh></v>
<v t="iggu.20190920201307.11"><vh>@item open-leo-docs-leo</vh></v>
<v t="iggu.20190920201307.12"><vh>@item open-leo-dist-leo</vh></v>
<v t="iggu.20190920201307.13"><vh>@item open-leo-plugins-leo</vh></v>
<v t="iggu.20190920201307.14"><vh>@item open-leo-py-leo</vh></v>
<v t="iggu.20190920201307.15"><vh>@item open-my-leo-settings</vh></v>
<v t="iggu.20190920201307.16"><vh>@item open-quickstart-leo</vh></v>
<v t="iggu.20190920201307.17"><vh>@item open-scripts-leo</vh></v>
<v t="iggu.20190920201307.18"><vh>@item open-leo-settings</vh></v>
<v t="iggu.20190920201307.19"><vh>@item open-unittest-leo</vh></v>
</v>
<v t="iggu.20190920201307.20"><vh>@menu Recent Files</vh></v>
<v t="iggu.20190920201307.21"><vh>@item -</vh></v>
<v t="iggu.20190920201307.22"><vh>@item save-file</vh></v>
<v t="iggu.20190920201307.23"><vh>@item save-file-as</vh></v>
<v t="iggu.20190920201307.24"><vh>@item save-file-as-unzipped</vh></v>
<v t="iggu.20190920201307.25"><vh>@item save-file-as-zipped</vh></v>
<v t="iggu.20190920201307.26"><vh>@item save-file-to</vh></v>
<v t="iggu.20190920201307.27"><vh>@item -</vh></v>
<v t="iggu.20190920201307.28"><vh>@menu &amp;Compare/Diff Files</vh>
<v t="iggu.20190920201307.29"><vh>@item file-&amp;compare-two-leo-files</vh></v>
<v t="iggu.20190920201307.30"><vh>@item file-diff-&amp;files</vh></v>
</v>
<v t="iggu.20190920201307.31"><vh>@menu &amp;Create/Remove Files Or Directories</vh>
<v t="iggu.20190920201307.32"><vh>@item directory-&amp;make</vh></v>
<v t="iggu.20190920201307.33"><vh>@item directory-&amp;remove</vh></v>
<v t="iggu.20190920201307.34"><vh>@item -</vh></v>
<v t="iggu.20190920201307.35"><vh>@item file-&amp;delete</vh></v>
<v t="iggu.20190920201307.36"><vh>@item file-&amp;insert</vh></v>
</v>
<v t="iggu.20190920201307.37"><vh>@menu &amp;Read/Write Files</vh>
<v t="iggu.20190920201307.38"><vh>@item check-derived-file</vh></v>
<v t="iggu.20190920201307.39"><vh>@@@item check-leo-file</vh></v>
<v t="iggu.20190920201307.40"><vh>@item file-compare-two-leo-files</vh></v>
<v t="iggu.20190920201307.41"><vh>@item -</vh></v>
<v t="iggu.20190920201307.42"><vh>@item read-outline-only</vh></v>
<v t="iggu.20190920201307.43"><vh>@item read-file-into-node</vh></v>
<v t="iggu.20190920201307.44"><vh>@item read-at-auto-nodes</vh></v>
<v t="iggu.20190920201307.45"><vh>@item read-at-file-nodes</vh></v>
<v t="iggu.20190920201307.46"><vh>@item read-at-shadow-nodes</vh></v>
<v t="iggu.20190920201307.47"><vh>@item -</vh></v>
<v t="iggu.20190920201307.48"><vh>@item write-outline-only</vh></v>
<v t="iggu.20190920201307.49"><vh>@item write-file-from-node</vh></v>
<v t="iggu.20190920201307.50"><vh>@item write-at-auto-nodes</vh></v>
<v t="iggu.20190920201307.51"><vh>@item write-at-file-nodes</vh></v>
<v t="iggu.20190920201307.52"><vh>@item write-at-shadow-nodes</vh></v>
<v t="iggu.20190920201307.53"><vh>@item -</vh></v>
<v t="iggu.20190920201307.54"><vh>@item write-dirty-at-auto-nodes</vh></v>
<v t="iggu.20190920201307.55"><vh>@item write-dirty-at-file-nodes</vh></v>
<v t="iggu.20190920201307.56"><vh>@item write-dirty-at-shadow-nodes</vh></v>
<v t="iggu.20190920201307.57"><vh>@item write-missing-at-file-nodes</vh></v>
</v>
<v t="iggu.20190920201307.58"><vh>@menu &amp;Import Files</vh>
<v t="iggu.20190920201307.59"><vh>@item import-file</vh></v>
<v t="iggu.20190920201307.60"><vh>@item import-free-mind-files</vh></v>
<v t="iggu.20190920201307.61"><vh>@item import-mind-jet-files</vh></v>
<v t="iggu.20190920201307.62"><vh>@item import-MORE-files</vh></v>
<v t="iggu.20190920201307.63"><vh>@item import-jupyter-notebook</vh></v>
<v t="iggu.20190920201307.64"><vh>@item import-tabbed-files</vh></v>
<v t="iggu.20190920201307.65"><vh>@item import-zim-folder</vh></v>
</v>
<v t="iggu.20190920201307.66"><vh>@menu &amp;Export Files</vh>
<v t="iggu.20190920201307.67"><vh>@item export-headlines</vh></v>
<v t="iggu.20190920201307.68"><vh>@item export-jupyter-notebook</vh></v>
<v t="iggu.20190920201307.69"><vh>@item flatten-outline</vh></v>
<v t="iggu.20190920201307.70"><vh>@item outline-to-cweb</vh></v>
<v t="iggu.20190920201307.71"><vh>@item outline-to-noweb</vh></v>
<v t="iggu.20190920201307.72"><vh>@item remove-sentinels</vh></v>
<v t="iggu.20190920201307.73"><vh>@item weave</vh></v>
</v>
<v t="iggu.20190920201307.74"><vh>@menu &amp;Print</vh>
<v t="iggu.20190920201307.75"><vh>@item print-body	</vh></v>
<v t="iggu.20190920201307.76"><vh>@item print-html</vh></v>
<v t="iggu.20190920201307.77"><vh>@item print-node</vh></v>
<v t="iggu.20190920201307.78"><vh>@item -</vh></v>
<v t="iggu.20190920201307.79"><vh>@item print-expanded-body</vh></v>
<v t="iggu.20190920201307.80"><vh>@item print-expanded-html</vh></v>
<v t="iggu.20190920201307.81"><vh>@item -</vh></v>
<v t="iggu.20190920201307.82"><vh>@item print-marked-bodies</vh></v>
<v t="iggu.20190920201307.83"><vh>@item print-marked-html</vh></v>
<v t="iggu.20190920201307.84"><vh>@item print-marked-nodes</vh></v>
<v t="iggu.20190920201307.85"><vh>@item -</vh></v>
<v t="iggu.20190920201307.86"><vh>@item print-tree-nodes</vh></v>
<v t="iggu.20190920201307.87"><vh>@item print-tree-bodies</vh></v>
<v t="iggu.20190920201307.88"><vh>@item print-tree-html</vh></v>
</v>
<v t="iggu.20190920201307.89"><vh>@menu &amp;Print Preview</vh>
<v t="iggu.20190920201307.90"><vh>@item preview-body	</vh></v>
<v t="iggu.20190920201307.91"><vh>@item preview-html</vh></v>
<v t="iggu.20190920201307.92"><vh>@item preview-node</vh></v>
<v t="iggu.20190920201307.93"><vh>@item -</vh></v>
<v t="iggu.20190920201307.94"><vh>@item preview-expanded-body</vh></v>
<v t="iggu.20190920201307.95"><vh>@item preview-expanded-html</vh></v>
<v t="iggu.20190920201307.96"><vh>@item -</vh></v>
<v t="iggu.20190920201307.97"><vh>@item preview-marked-bodies</vh></v>
<v t="iggu.20190920201307.98"><vh>@item preview-marked-html</vh></v>
<v t="iggu.20190920201307.99"><vh>@item preview-marked-nodes</vh></v>
<v t="iggu.20190920201307.100"><vh>@item -</vh></v>
<v t="iggu.20190920201307.101"><vh>@item preview-tree-nodes</vh></v>
<v t="iggu.20190920201307.102"><vh>@item preview-tree-bodies</vh></v>
<v t="iggu.20190920201307.103"><vh>@item preview-tree-html</vh></v>
</v>
<v t="iggu.20190920201307.104"><vh>@menu &amp;Revert/Refresh Files</vh>
<v t="iggu.20190920201307.105"><vh>@item refresh-from-disk</vh></v>
<v t="iggu.20190920201307.106"><vh>@item revert</vh></v>
</v>
<v t="iggu.20190920201307.107"><vh>@item -</vh></v>
<v t="iggu.20190920201307.108"><vh>@item exit-leo</vh></v>
</v>
<v t="iggu.20190920201307.109"><vh>@menu Edit</vh>
<v t="iggu.20190920201307.110"><vh>@item &amp;undo</vh></v>
<v t="iggu.20190920201307.111"><vh>@item &amp;redo</vh></v>
<v t="iggu.20190920201307.112"><vh>@item -</vh></v>
<v t="iggu.20190920201307.113"><vh>@item &amp;cut-text</vh></v>
<v t="iggu.20190920201307.114"><vh>@item &amp;copy-text</vh></v>
<v t="iggu.20190920201307.115"><vh>@item &amp;paste-text</vh></v>
<v t="iggu.20190920201307.116"><vh>@item &amp;select-all</vh></v>
<v t="iggu.20190920201307.117"><vh>@item -</vh></v>
<v t="iggu.20190920201307.118"><vh>@menu &amp;Check Spelling</vh>
<v t="iggu.20190920201307.119"><vh>@item &amp;spell-tab-open</vh></v>
<v t="iggu.20190920201307.120"><vh>@item spell-&amp;change</vh></v>
<v t="iggu.20190920201307.121"><vh>@item spell-change-&amp;then-find</vh></v>
<v t="iggu.20190920201307.122"><vh>@item spell-&amp;find</vh></v>
<v t="iggu.20190920201307.123"><vh>@item spell-&amp;ignore</vh></v>
</v>
<v t="iggu.20190920201307.124"><vh>@menu &amp;Edit Headline</vh>
<v t="iggu.20190920201307.125"><vh>@item edit-&amp;headline</vh></v>
<v t="iggu.20190920201307.126"><vh>@item &amp;end-edit-headline</vh></v>
<v t="iggu.20190920201307.127"><vh>@item &amp;abort-edit-headline</vh></v>
<v t="iggu.20190920201307.128"><vh>@item insert-headline-&amp;time</vh></v>
</v>
<v t="iggu.20190920201307.129"><vh>@menu &amp;Edit Text</vh>
<v t="iggu.20190920201307.130"><vh>@item &amp;backward-delete-char</vh></v>
<v t="iggu.20190920201307.131"><vh>@item -</vh></v>
<v t="iggu.20190920201307.132"><vh>@menu &amp;Add/Delete Comments</vh>
<v t="iggu.20190920201307.133"><vh>@item &amp;add-comments</vh></v>
<v t="iggu.20190920201307.134"><vh>@item &amp;delete-comments</vh></v>
</v>
<v t="iggu.20190920201307.135"><vh>@menu &amp;Align text</vh>
<v t="iggu.20190920201307.136"><vh>@item center-&amp;line</vh></v>
<v t="iggu.20190920201307.137"><vh>@item center-&amp;region</vh></v>
</v>
<v t="iggu.20190920201307.138"><vh>@menu &amp;Beautify Text</vh>
<v t="iggu.20190920201307.139"><vh>@item beautify-&amp;c</vh></v>
<v t="iggu.20190920201307.140"><vh>@item &amp;beautify-node</vh></v>
<v t="iggu.20190920201307.141"><vh>@item beautify-&amp;tree</vh></v>
</v>
<v t="iggu.20190920201307.142"><vh>@menu &amp;Capitalize Text</vh>
<v t="iggu.20190920201307.143"><vh>@item &amp;capitalize-word</vh></v>
<v t="iggu.20190920201307.144"><vh>@item d&amp;owncase-region</vh></v>
<v t="iggu.20190920201307.145"><vh>@item &amp;downcase-word</vh></v>
<v t="iggu.20190920201307.146"><vh>@item u&amp;pcase-region</vh></v>
<v t="iggu.20190920201307.147"><vh>@item &amp;upcase-word</vh></v>
</v>
<v t="iggu.20190920201307.148"><vh>@menu &amp;Convert/View Tabs Or Blanks</vh>
<v t="iggu.20190920201307.149"><vh>@item convert-all-b&amp;lanks</vh></v>
<v t="iggu.20190920201307.150"><vh>@item convert-all-t&amp;abs</vh></v>
<v t="iggu.20190920201307.151"><vh>@item convert-&amp;blanks</vh></v>
<v t="iggu.20190920201307.152"><vh>@item convert-&amp;tabs</vh></v>
<v t="iggu.20190920201307.153"><vh>@item &amp;toggle-invisibles</vh></v>
</v>
<v t="iggu.20190920201307.154"><vh>@menu &amp;Create Sections</vh>
<v t="iggu.20190920201307.155"><vh>@item extract-&amp;names</vh></v>
<v t="iggu.20190920201307.156"><vh>@item &amp;extract</vh></v>
</v>
<v t="iggu.20190920201307.157"><vh>@menu &amp;Edit Rectangular Areas</vh>
<v t="iggu.20190920201307.158"><vh>@item rectangle-&amp;clear</vh></v>
<v t="iggu.20190920201307.159"><vh>@item rectangle-&amp;close</vh></v>
<v t="iggu.20190920201307.160"><vh>@item rectangle-&amp;delete</vh></v>
<v t="iggu.20190920201307.161"><vh>@item rectangle-&amp;kill</vh></v>
<v t="iggu.20190920201307.162"><vh>@item rectangle-&amp;open</vh></v>
<v t="iggu.20190920201307.163"><vh>@item rectangle-&amp;string</vh></v>
<v t="iggu.20190920201307.164"><vh>@item rectangle-&amp;yank</vh></v>
</v>
<v t="iggu.20190920201307.165"><vh>@menu &amp;Indent Text</vh>
<v t="iggu.20190920201307.166"><vh>@item indent-ri&amp;gidly</vh></v>
<v t="iggu.20190920201307.167"><vh>@item &amp;indent-region</vh></v>
<v t="iggu.20190920201307.168"><vh>@item indent-r&amp;elative</vh></v>
<v t="iggu.20190920201307.169"><vh>@item u&amp;nindent-region</vh></v>
</v>
<v t="iggu.20190920201307.170"><vh>@menu &amp;Move Cursor And Make Selections</vh>
<v t="iggu.20190920201307.171"><vh>@item &amp;match-brackets</vh></v>
<v t="iggu.20190920201307.172"><vh>@item -</vh></v>
<v t="iggu.20190920201307.173"><vh>@menu Cursor &amp;Back</vh>
<v t="iggu.20190920201307.174"><vh>@item back-&amp;char</vh></v>
<v t="iggu.20190920201307.175"><vh>@item back-&amp;paragraph</vh></v>
<v t="iggu.20190920201307.176"><vh>@item back-&amp;sentence</vh></v>
<v t="iggu.20190920201307.177"><vh>@item back-&amp;word</vh></v>
<v t="iggu.20190920201307.178"><vh>@item -</vh></v>
<v t="iggu.20190920201307.179"><vh>@item beginning-of-&amp;buffer</vh></v>
<v t="iggu.20190920201307.180"><vh>@item beginning-of-&amp;line</vh></v>
<v t="iggu.20190920201307.181"><vh>@item -</vh></v>
<v t="iggu.20190920201307.182"><vh>@item pre&amp;vious-line</vh></v>
</v>
<v t="iggu.20190920201307.183"><vh>@menu Cursor Back &amp;Extend Selection</vh>
<v t="iggu.20190920201307.184"><vh>@item back-&amp;char-extend-selection</vh></v>
<v t="iggu.20190920201307.185"><vh>@item back-&amp;paragraph-extend-selection</vh></v>
<v t="iggu.20190920201307.186"><vh>@item back-&amp;sentence-extend-selection</vh></v>
<v t="iggu.20190920201307.187"><vh>@item back-&amp;word-extend-selection</vh></v>
<v t="iggu.20190920201307.188"><vh>@item -</vh></v>
<v t="iggu.20190920201307.189"><vh>@item beginning-of-&amp;buffer-extend-selection</vh></v>
<v t="iggu.20190920201307.190"><vh>@item beginning-of-&amp;line-extend-selection</vh></v>
<v t="iggu.20190920201307.191"><vh>@item -</vh></v>
<v t="iggu.20190920201307.192"><vh>@item pre&amp;vious-line-extend-selection</vh></v>
</v>
<v t="iggu.20190920201307.193"><vh>@menu Cursor Back Extend &amp;to</vh>
<v t="iggu.20190920201307.194"><vh>@item extend-to-&amp;line</vh></v>
<v t="iggu.20190920201307.195"><vh>@item extend-to-&amp;paragraph</vh></v>
<v t="iggu.20190920201307.196"><vh>@item extend-to-&amp;sentence</vh></v>
<v t="iggu.20190920201307.197"><vh>@item extend-to-&amp;word</vh></v>
</v>
<v t="iggu.20190920201307.198"><vh>@menu Cursor &amp;Forward</vh>
<v t="iggu.20190920201307.199"><vh>@item end-of-&amp;buffer</vh></v>
<v t="iggu.20190920201307.200"><vh>@item end-of-&amp;line</vh></v>
<v t="iggu.20190920201307.201"><vh>@item -</vh></v>
<v t="iggu.20190920201307.202"><vh>@item forward-&amp;char</vh></v>
<v t="iggu.20190920201307.203"><vh>@item forward-&amp;paragraph</vh></v>
<v t="iggu.20190920201307.204"><vh>@item forward-&amp;sentence</vh></v>
<v t="iggu.20190920201307.205"><vh>@item forward-&amp;end-word</vh></v>
<v t="iggu.20190920201307.206"><vh>@item forward-&amp;word</vh></v>
<v t="iggu.20190920201307.207"><vh>@item -</vh></v>
<v t="iggu.20190920201307.208"><vh>@item &amp;next-line</vh></v>
</v>
<v t="iggu.20190920201307.209"><vh>@menu Cursor Forward E&amp;xtend Selection</vh>
<v t="iggu.20190920201307.210"><vh>@item end-of-&amp;buffer-extend-selection</vh></v>
<v t="iggu.20190920201307.211"><vh>@item end-of-&amp;line-extend-selection</vh></v>
<v t="iggu.20190920201307.212"><vh>@item -</vh></v>
<v t="iggu.20190920201307.213"><vh>@item forward-&amp;char-extend-selection</vh></v>
<v t="iggu.20190920201307.214"><vh>@item forward-&amp;paragraph-extend-selection</vh></v>
<v t="iggu.20190920201307.215"><vh>@item forward-&amp;sentence-extend-selection</vh></v>
<v t="iggu.20190920201307.216"><vh>@item forward-&amp;end-word-extend-selection</vh></v>
<v t="iggu.20190920201307.217"><vh>@item forward-&amp;word-extend-selection</vh></v>
<v t="iggu.20190920201307.218"><vh>@item -</vh></v>
<v t="iggu.20190920201307.219"><vh>@item &amp;next-line-extend-selection</vh></v>
</v>
</v>
<v t="iggu.20190920201307.220"><vh>@menu &amp;Sort Text</vh>
<v t="iggu.20190920201307.221"><vh>@item sort-&amp;columns</vh></v>
<v t="iggu.20190920201307.222"><vh>@item sort-&amp;fields</vh></v>
<v t="iggu.20190920201307.223"><vh>@item sort-&amp;lines</vh></v>
</v>
<v t="iggu.20190920201307.224"><vh>@menu &amp;Yank/Kill Text</vh>
<v t="iggu.20190920201307.225"><vh>@item &amp;rectangle-kill</vh></v>
<v t="iggu.20190920201307.226"><vh>@item r&amp;ectangle-yank</vh></v>
<v t="iggu.20190920201307.227"><vh>@item -</vh></v>
<v t="iggu.20190920201307.228"><vh>@item kill-&amp;line</vh></v>
<v t="iggu.20190920201307.229"><vh>@item kill-re&amp;gion</vh></v>
<v t="iggu.20190920201307.230"><vh>@item kill-region-s&amp;ave</vh></v>
<v t="iggu.20190920201307.231"><vh>@item kill-&amp;sentence</vh></v>
<v t="iggu.20190920201307.232"><vh>@item kill-ws</vh></v>
<v t="iggu.20190920201307.233"><vh>@item kill-&amp;word</vh></v>
<v t="iggu.20190920201307.234"><vh>@item -</vh></v>
<v t="iggu.20190920201307.235"><vh>@item &amp;yank</vh></v>
<v t="iggu.20190920201307.236"><vh>@item yank-&amp;pop</vh></v>
</v>
</v>
<v t="iggu.20190920201307.237"><vh>@menu &amp;Format Text</vh>
<v t="iggu.20190920201307.238"><vh>@item &amp;code-to-rst</vh></v>
<v t="iggu.20190920201307.239"><vh>@item &amp;insert-body-&amp;time</vh></v>
<v t="iggu.20190920201307.240"><vh>@item &amp;reformat-paragraph</vh></v>
<v t="iggu.20190920201307.241"><vh>@item &amp;rst3</vh></v>
</v>
<v t="iggu.20190920201307.242"><vh>@menu &amp;Select Chapters</vh>
<v t="iggu.20190920201307.243"><vh>@item chapter-&amp;select</vh></v>
<v t="iggu.20190920201307.244"><vh>@item chapter-select-&amp;main</vh></v>
</v>
</v>
<v t="iggu.20190920201307.245"><vh>@menu Search</vh>
<v t="iggu.20190920201307.246"><vh>@item help-for-find-commands</vh></v>
<v t="iggu.20190920201307.247"><vh>@item -</vh></v>
<v t="iggu.20190920201307.248"><vh>@item &amp;goto-global-line</vh></v>
<v t="iggu.20190920201307.249"><vh>@item start-search</vh></v>
<v t="iggu.20190920201307.250"><vh>@item find-&amp;next</vh></v>
<v t="iggu.20190920201307.251"><vh>@item find-&amp;prev</vh></v>
<v t="iggu.20190920201307.252"><vh>@item &amp;replace</vh></v>
<v t="iggu.20190920201307.253"><vh>@item replace-&amp;then-find</vh></v>
<v t="iggu.20190920201307.254"><vh>@item replace-a&amp;ll</vh></v>
<v t="iggu.20190920201307.255"><vh>@item show-find-&amp;options</vh></v>
<v t="iggu.20190920201307.256"><vh>@item -</vh></v>
<v t="iggu.20190920201307.257"><vh>@menu &amp;Clone-Find Commands</vh>
<v t="iggu.20190920201307.258"><vh>@item clone-find-all</vh></v>
<v t="iggu.20190920201307.259"><vh>@item clone-find-all-flattened</vh></v>
<v t="iggu.20190920201307.260"><vh>@item clone-find-all-flattened-marked</vh></v>
<v t="iggu.20190920201307.261"><vh>@item clone-find-parents</vh></v>
<v t="iggu.20190920201307.262"><vh>@item clone-find-tag</vh></v>
</v>
<v t="iggu.20190920201307.263"><vh>@menu &amp;Set Search Settings</vh>
<v t="iggu.20190920201307.264"><vh>@item &amp;set-find-everywhere</vh></v>
<v t="iggu.20190920201307.265"><vh>@item &amp;set-find-node-only</vh></v>
<v t="iggu.20190920201307.266"><vh>@item &amp;set-find-suboutline-only</vh></v>
<v t="iggu.20190920201307.267"><vh>@item -</vh></v>
<v t="iggu.20190920201307.268"><vh>@item &amp;toggle-find-ignore-case-option</vh></v>
<v t="iggu.20190920201307.269"><vh>@item &amp;toggle-find-mark-changes-option</vh></v>
<v t="iggu.20190920201307.270"><vh>@item &amp;toggle-find-mark-finds-option</vh></v>
<v t="iggu.20190920201307.271"><vh>@item &amp;toggle-find-regex-option</vh></v>
<v t="iggu.20190920201307.272"><vh>@item &amp;toggle-find-word-option</vh></v>
<v t="iggu.20190920201307.273"><vh>@item &amp;toggle-find-wrap-around-option</vh></v>
</v>
<v t="iggu.20190920201307.274"><vh>@menu &amp;Find One Character</vh>
<v t="iggu.20190920201307.275"><vh>@item &amp;find-character</vh></v>
<v t="iggu.20190920201307.276"><vh>@item &amp;find-character-extend-selection</vh></v>
<v t="iggu.20190920201307.277"><vh>@item &amp;backward-find-character</vh></v>
<v t="iggu.20190920201307.278"><vh>@item &amp;backward-find-character-extend-selection</vh></v>
</v>
<v t="iggu.20190920201307.279"><vh>@menu &amp;Find Incrementally</vh>
<v t="iggu.20190920201307.280"><vh>@item &amp;isearch-forward</vh></v>
<v t="iggu.20190920201307.281"><vh>@item isea&amp;rch-backward</vh></v>
<v t="iggu.20190920201307.282"><vh>@item isearch-forward-rege&amp;xp</vh></v>
<v t="iggu.20190920201307.283"><vh>@item isearch-backward-regex&amp;p</vh></v>
</v>
</v>
<v t="iggu.20190920201307.284"><vh>@menu Settings</vh>
<v t="iggu.20190920201307.285"><vh>@item open-leo-settings</vh></v>
<v t="iggu.20190920201307.286"><vh>@item open-my-leo-settings</vh></v>
<v t="iggu.20190920201307.287"><vh>@item open-theme-file</vh></v>
<v t="iggu.20190920201307.288"><vh>@item open-local-settings</vh></v>
<v t="iggu.20190920201307.289"><vh>@item -</vh></v>
<v t="iggu.20190920201307.290"><vh>@menu &amp;List/Kill Abbreviations</vh>
<v t="iggu.20190920201307.291"><vh>@item abbrev-&amp;list</vh></v>
<v t="iggu.20190920201307.292"><vh>@item abbrev-&amp;kill-all</vh></v>
</v>
<v t="iggu.20190920201307.293"><vh>@menu &amp;Pick Colors/Fonts</vh>
<v t="iggu.20190920201307.294"><vh>@item show-color-&amp;names</vh></v>
<v t="iggu.20190920201307.295"><vh>@item show-color-&amp;wheel</vh></v>
<v t="iggu.20190920201307.296"><vh>@item show-&amp;fonts</vh></v>
</v>
<v t="iggu.20190920201307.297"><vh>@menu &amp;Reload Settings</vh>
<v t="iggu.20190920201307.298"><vh>@item reload-all-settings</vh></v>
<v t="iggu.20190920201307.299"><vh>@item reload-settings</vh></v>
<v t="iggu.20190920201307.300"><vh>@item reload-style-sheets</vh></v>
</v>
<v t="iggu.20190920201307.301"><vh>@menu &amp;Show Settings</vh>
<v t="iggu.20190920201307.302"><vh>@item show-&amp;bindings</vh></v>
<v t="iggu.20190920201307.303"><vh>@item show-&amp;commands</vh></v>
<v t="iggu.20190920201307.304"><vh>@item show-&amp;settings</vh></v>
<v t="iggu.20190920201307.305"><vh>@item show-&amp;plugins-info</vh></v>
</v>
<v t="iggu.20190920201307.306"><vh>@menu &amp;Toggle Settings</vh>
<v t="iggu.20190920201307.307"><vh>@item toggle-a&amp;utocompleter</vh></v>
<v t="iggu.20190920201307.308"><vh>@item toggle-call&amp;tips</vh></v>
<v t="iggu.20190920201307.309"><vh>@item toggle-&amp;extend-mode</vh></v>
<v t="iggu.20190920201307.310"><vh>@item toggle-input-&amp;state</vh></v>
<v t="iggu.20190920201307.311"><vh>@item toggle-in&amp;visibles</vh></v>
<v t="iggu.20190920201307.312"><vh>@item toggle-split-&amp;direction</vh></v>
<v t="iggu.20190920201307.313"><vh>@item toggle-s&amp;parse-move</vh></v>
</v>
<v t="iggu.20190920201307.314"><vh>@item open-desktop-integration-leo</vh></v>
</v>
<v t="iggu.20190920201307.315"><vh>@menu Outline</vh>
<v t="iggu.20190920201307.316"><vh>@item &amp;clone-node</vh></v>
<v t="iggu.20190920201307.317"><vh>@item &amp;delete-node</vh></v>
<v t="iggu.20190920201307.318"><vh>@item &amp;insert-node</vh></v>
<v t="iggu.20190920201307.319"><vh>@item insert-child</vh></v>
<v t="iggu.20190920201307.320"><vh>@item -</vh></v>
<v t="iggu.20190920201307.321"><vh>@item c&amp;ut-node</vh></v>
<v t="iggu.20190920201307.322"><vh>@item c&amp;opy-node</vh></v>
<v t="iggu.20190920201307.323"><vh>@item &amp;paste-node</vh></v>
<v t="iggu.20190920201307.324"><vh>@item paste-retaining-clones</vh></v>
<v t="iggu.20190920201307.325"><vh>@item -</vh></v>
<v t="iggu.20190920201307.326"><vh>@menu &amp;Check/Dump Outline</vh>
<v t="iggu.20190920201307.327"><vh>@item check-&amp;outline</vh></v>
<v t="iggu.20190920201307.328"><vh>@item &amp;dump-outline</vh></v>
</v>
<v t="iggu.20190920201307.329"><vh>@menu &amp;Expand/Contract Nodes</vh>
<v t="iggu.20190920201307.330"><vh>Accel: a,c,d,e,n,o,p,l,r,t,x</vh></v>
<v t="iggu.20190920201307.331"><vh>@item &amp;contract-all</vh></v>
<v t="iggu.20190920201307.332"><vh>@item contract-all-o&amp;ther-nodes</vh></v>
<v t="iggu.20190920201307.333"><vh>@item contract-&amp;node</vh></v>
<v t="iggu.20190920201307.334"><vh>@item contract-&amp;parent</vh></v>
<v t="iggu.20190920201307.335"><vh>@item contract-or-go-&amp;left</vh></v>
<v t="iggu.20190920201307.336"><vh>@item -</vh></v>
<v t="iggu.20190920201307.337"><vh>@item expand-p&amp;rev-level</vh></v>
<v t="iggu.20190920201307.338"><vh>@item expand-n&amp;ext-level</vh></v>
<v t="iggu.20190920201307.339"><vh>@item e&amp;xpand-and-go-right</vh></v>
<v t="iggu.20190920201307.340"><vh>@item expan&amp;d-or-go-right</vh></v>
<v t="iggu.20190920201307.341"><vh>@item -</vh></v>
<v t="iggu.20190920201307.342"><vh>@item expand-to-level-&amp;1</vh></v>
<v t="iggu.20190920201307.343"><vh>@item expand-to-level-&amp;2</vh></v>
<v t="iggu.20190920201307.344"><vh>@item expand-to-level-&amp;3</vh></v>
<v t="iggu.20190920201307.345"><vh>@item expand-to-level-&amp;4</vh></v>
<v t="iggu.20190920201307.346"><vh>@item expand-to-level-&amp;5</vh></v>
<v t="iggu.20190920201307.347"><vh>@item expand-to-level-&amp;6</vh></v>
<v t="iggu.20190920201307.348"><vh>@item expand-to-level-&amp;7</vh></v>
<v t="iggu.20190920201307.349"><vh>@item expand-to-level-&amp;8</vh></v>
<v t="iggu.20190920201307.350"><vh>@item -</vh></v>
<v t="iggu.20190920201307.351"><vh>@item expand-&amp;all</vh></v>
<v t="iggu.20190920201307.352"><vh>@item expand-n&amp;ode</vh></v>
</v>
<v t="iggu.20190920201307.353"><vh>@menu &amp;Go To Node</vh>
<v t="iggu.20190920201307.354"><vh>@item find-next-clone</vh></v>
<v t="iggu.20190920201307.355"><vh>@item goto-first-node</vh></v>
<v t="iggu.20190920201307.356"><vh>@item goto-first-visible-node</vh></v>
<v t="iggu.20190920201307.357"><vh>@item goto-first-sibling</vh></v>
<v t="iggu.20190920201307.358"><vh>@item -</vh></v>
<v t="iggu.20190920201307.359"><vh>@item goto-next-changed</vh></v>
<v t="iggu.20190920201307.360"><vh>@item goto-next-clone</vh></v>
<v t="iggu.20190920201307.361"><vh>@item goto-next-marked</vh></v>
<v t="iggu.20190920201307.362"><vh>@item goto-next-node</vh></v>
<v t="iggu.20190920201307.363"><vh>@item goto-next-sibling</vh></v>
<v t="iggu.20190920201307.364"><vh>@item goto-next-visible</vh></v>
<v t="iggu.20190920201307.365"><vh>@item go-forward</vh></v>
<v t="iggu.20190920201307.366"><vh>@item -</vh></v>
<v t="iggu.20190920201307.367"><vh>@item goto-parent</vh></v>
<v t="iggu.20190920201307.368"><vh>@item -</vh></v>
<v t="iggu.20190920201307.369"><vh>@item goto-prev-node</vh></v>
<v t="iggu.20190920201307.370"><vh>@item goto-prev-sibling</vh></v>
<v t="iggu.20190920201307.371"><vh>@item goto-prev-visible</vh></v>
<v t="iggu.20190920201307.372"><vh>@item go-back</vh></v>
<v t="iggu.20190920201307.373"><vh>@item -</vh></v>
<v t="iggu.20190920201307.374"><vh>@item goto-last-node</vh></v>
<v t="iggu.20190920201307.375"><vh>@item goto-last-sibling</vh></v>
<v t="iggu.20190920201307.376"><vh>@item goto-last-visible-node</vh></v>
</v>
<v t="iggu.20190920201307.377"><vh>@menu &amp;Hoist/Dehoist nodes</vh>
<v t="iggu.20190920201307.378"><vh>@item &amp;hoist</vh></v>
<v t="iggu.20190920201307.379"><vh>@item de-hoist</vh></v>
</v>
<v t="iggu.20190920201307.380"><vh>@menu &amp;Insert/Delete Icons</vh>
<v t="iggu.20190920201307.381"><vh>@item delete-&amp;first-icon</vh></v>
<v t="iggu.20190920201307.382"><vh>@item delete-&amp;last-icon</vh></v>
<v t="iggu.20190920201307.383"><vh>@item delete-&amp;node-icons</vh></v>
<v t="iggu.20190920201307.384"><vh>@item &amp;insert-icon</vh></v>
</v>
<v t="iggu.20190920201307.385"><vh>@menu &amp;Mark Nodes</vh>
<v t="iggu.20190920201307.386"><vh>@item clone-marked-nodes</vh></v>
<v t="iggu.20190920201307.387"><vh>@item &amp;mark</vh></v>
<v t="iggu.20190920201307.388"><vh>@item mark-&amp;subheads</vh></v>
<v t="iggu.20190920201307.389"><vh>@item mark-changed-&amp;items</vh></v>
<v t="iggu.20190920201307.390"><vh>@item &amp;unmark-all</vh></v>
</v>
<v t="iggu.20190920201307.391"><vh>@menu &amp;Move Nodes</vh>
<v t="iggu.20190920201307.392"><vh>@item move-outline-down</vh></v>
<v t="iggu.20190920201307.393"><vh>@item move-outline-left</vh></v>
<v t="iggu.20190920201307.394"><vh>@item move-outline-right</vh></v>
<v t="iggu.20190920201307.395"><vh>@item move-outline-up</vh></v>
<v t="iggu.20190920201307.396"><vh>@item -</vh></v>
<v t="iggu.20190920201307.397"><vh>@item &amp;promote</vh></v>
<v t="iggu.20190920201307.398"><vh>@item &amp;demote</vh></v>
</v>
<v t="iggu.20190920201307.399"><vh>@menu &amp;Sort Nodes</vh>
<v t="iggu.20190920201307.400"><vh>@item sort-childre&amp;n</vh></v>
<v t="iggu.20190920201307.401"><vh>@item &amp;sort-siblings</vh></v>
</v>
</v>
<v t="iggu.20190920201307.402"><vh>@menu Plugins</vh>
<v t="iggu.20190920201307.403"><vh>@item open-leo-plugins-leo</vh></v>
<v t="iggu.20190920201307.404"><vh>@item show-plugins-info</vh></v>
<v t="iggu.20190920201307.405"><vh>@item -</vh></v>
</v>
<v t="iggu.20190920201307.406"><vh>@menu Run</vh>
<v t="iggu.20190920201307.407"><vh>@item &amp;help-for-minibuffer</vh></v>
<v t="iggu.20190920201307.408"><vh>@item &amp;execute-script</vh></v>
<v t="iggu.20190920201307.409"><vh>@item &amp;full-command</vh></v>
<v t="iggu.20190920201307.410"><vh>@item &amp;keyboard-quit</vh></v>
<v t="iggu.20190920201307.411"><vh>@item &amp;repeat-complex-command</vh></v>
<v t="iggu.20190920201307.412"><vh>@item &amp;view-lossage</vh></v>
<v t="iggu.20190920201307.413"><vh>@item -</vh></v>
<v t="iggu.20190920201307.414"><vh>@item &amp;eval</vh></v>
<v t="iggu.20190920201307.415"><vh>@item &amp;eval-block</vh></v>
<v t="iggu.20190920201307.416"><vh>@item &amp;eval-last</vh></v>
<v t="iggu.20190920201307.417"><vh>@item &amp;eval-last-pretty</vh></v>
<v t="iggu.20190920201307.418"><vh>@item &amp;eval-replace</vh></v>
<v t="iggu.20190920201307.419"><vh>@item -</vh></v>
<v t="iggu.20190920201307.420"><vh>@menu &amp;Control Garbage Collection</vh>
<v t="iggu.20190920201307.421"><vh>@item gc-&amp;collect-garbage</vh></v>
<v t="iggu.20190920201307.422"><vh>@item gc-dump-&amp;all-objects</vh></v>
<v t="iggu.20190920201307.423"><vh>@item gc-dump-&amp;new-objects</vh></v>
<v t="iggu.20190920201307.424"><vh>@item gc-dump-objects-&amp;verbose</vh></v>
<v t="iggu.20190920201307.425"><vh>@item gc-show-&amp;summary</vh></v>
</v>
<v t="iggu.20190920201307.426"><vh>@menu &amp;Execute Shell Commands</vh>
<v t="iggu.20190920201307.427"><vh>@item &amp;open-python-window</vh></v>
<v t="iggu.20190920201307.428"><vh>@item &amp;shell-command</vh></v>
<v t="iggu.20190920201307.429"><vh>@item &amp;shell-command-on-region</vh></v>
</v>
<v t="iggu.20190920201307.430"><vh>@menu &amp;Invoke Debuggers</vh>
<v t="iggu.20190920201307.431"><vh>@item debug</vh></v>
<v t="iggu.20190920201307.432"><vh>@item pdb</vh></v>
</v>
<v t="iggu.20190920201307.433"><vh>@menu &amp;Run Unit Tests</vh>
<v t="iggu.20190920201307.434"><vh>@item run-&amp;all-unit-tests-locally</vh></v>
<v t="iggu.20190920201307.435"><vh>@item run-&amp;marked-unit-tests-locally</vh></v>
<v t="iggu.20190920201307.436"><vh>@item run-&amp;selected-unit-tests-locally</vh></v>
<v t="iggu.20190920201307.437"><vh>@item -</vh></v>
<v t="iggu.20190920201307.438"><vh>@item run-&amp;all-unit-tests-externally</vh></v>
<v t="iggu.20190920201307.439"><vh>@item run-&amp;marked-unit-tests-externally</vh></v>
<v t="iggu.20190920201307.440"><vh>@item run-&amp;selected-unit-tests-externally</vh></v>
</v>
</v>
<v t="iggu.20190920201307.441"><vh>@menu Window</vh>
<v t="iggu.20190920201307.442"><vh>@item &amp;cascade-windows</vh></v>
<v t="iggu.20190920201307.443"><vh>@item &amp;equal-sized-panes</vh></v>
<v t="iggu.20190920201307.444"><vh>@item &amp;minimize-all</vh></v>
<v t="iggu.20190920201307.445"><vh>@item &amp;resize-to-screen</vh></v>
<v t="iggu.20190920201307.446"><vh>@item toggle-&amp;split-direction</vh></v>
<v t="iggu.20190920201307.447"><vh>@item -</vh></v>
<v t="iggu.20190920201307.448"><vh>@menu &amp;Add/Delete Body Editors</vh>
<v t="iggu.20190920201307.449"><vh>@item &amp;add-editor</vh></v>
<v t="iggu.20190920201307.450"><vh>@item &amp;delete-editor</vh></v>
</v>
<v t="iggu.20190920201307.451"><vh>@menu &amp;Window Layout</vh>
<v t="iggu.20190920201307.452"><vh>@item free-layout-context-menu</vh></v>
<v t="iggu.20190920201307.453"><vh>@item free-layout-load</vh></v>
<v t="iggu.20190920201307.454"><vh>@item free-layout-restore</vh></v>
<v t="iggu.20190920201307.455"><vh>@item free-layout-zoom</vh></v>
<v t="iggu.20190920201307.456"><vh>@item -</vh></v>
<v t="iggu.20190920201307.457"><vh>@item show-hide-body-dock</vh></v>
<v t="iggu.20190920201307.458"><vh>@item show-hide-outline-dock</vh></v>
<v t="iggu.20190920201307.459"><vh>@item show-hide-render-dock</vh></v>
<v t="iggu.20190920201307.460"><vh>@item show-hide-tabs-dock</vh></v>
</v>
<v t="iggu.20190920201307.461"><vh>@menu &amp;Scroll Text Areas</vh>
<v t="iggu.20190920201307.462"><vh>@item scroll-outline-down-&amp;line</vh></v>
<v t="iggu.20190920201307.463"><vh>@item scroll-outline-down-&amp;page</vh></v>
<v t="iggu.20190920201307.464"><vh>@item scroll-outline-le&amp;ft</vh></v>
<v t="iggu.20190920201307.465"><vh>@item scroll-outline-&amp;right</vh></v>
<v t="iggu.20190920201307.466"><vh>@item s&amp;croll-outline-up-line</vh></v>
<v t="iggu.20190920201307.467"><vh>@item scr&amp;oll-outline-up-page</vh></v>
<v t="iggu.20190920201307.468"><vh>@item -</vh></v>
<v t="iggu.20190920201307.469"><vh>@item scroll-down-half-page</vh></v>
<v t="iggu.20190920201307.470"><vh>@item scroll-down-line</vh></v>
<v t="iggu.20190920201307.471"><vh>@item scroll-&amp;down-page</vh></v>
<v t="iggu.20190920201307.472"><vh>@item scroll-up-half-page</vh></v>
<v t="iggu.20190920201307.473"><vh>@item scroll-up-line</vh></v>
<v t="iggu.20190920201307.474"><vh>@item scroll-&amp;up-page</vh></v>
</v>
<v t="iggu.20190920201307.475"><vh>@menu &amp;Set Focus</vh>
<v t="iggu.20190920201307.476"><vh>@item &amp;toggle-active-pane</vh></v>
<v t="iggu.20190920201307.477"><vh>@item -</vh></v>
<v t="iggu.20190920201307.478"><vh>@item focus-to-&amp;body</vh></v>
<v t="iggu.20190920201307.479"><vh>@item focus-to-&amp;log</vh></v>
<v t="iggu.20190920201307.480"><vh>@item focus-to-&amp;find</vh></v>
<v t="iggu.20190920201307.481"><vh>@item focus-to-&amp;minibuffer</vh></v>
<v t="iggu.20190920201307.482"><vh>@item focus-to-&amp;spell-tab</vh></v>
<v t="iggu.20190920201307.483"><vh>@item focus-to-&amp;tree</vh></v>
</v>
</v>
<v t="iggu.20190920201307.484"><vh>@menu Help</vh>
<v t="iggu.20190920201307.485"><vh>@item &amp;about-leo</vh></v>
<v t="iggu.20190920201307.486"><vh>@item -</vh></v>
<v t="iggu.20190920201307.487"><vh>@menu &amp;Open Help topics</vh>
<v t="iggu.20190920201307.488"><vh>@item help</vh></v>
<v t="iggu.20190920201307.489"><vh>@item help-for-&amp;abbreviations</vh></v>
<v t="iggu.20190920201307.490"><vh>@item help-for-&amp;autocompletion</vh></v>
<v t="iggu.20190920201307.491"><vh>@item help-for-&amp;bindings</vh></v>
<v t="iggu.20190920201307.492"><vh>@item help-for-&amp;command</vh></v>
<v t="iggu.20190920201307.493"><vh>@item help-for-&amp;creating-external-files</vh></v>
<v t="iggu.20190920201307.494"><vh>@item help-for-&amp;drag-and-drop</vh></v>
<v t="iggu.20190920201307.495"><vh>@item help-for-&amp;debugging-commands</vh></v>
<v t="iggu.20190920201307.496"><vh>@item help-for-&amp;dynamic-abbreviations</vh></v>
<v t="iggu.20190920201307.497"><vh>@item help-for-&amp;find-commands</vh></v>
<v t="iggu.20190920201307.498"><vh>@item help-for-&amp;keystroke</vh></v>
<v t="iggu.20190920201307.499"><vh>@item help-for-&amp;minibuffer</vh></v>
<v t="iggu.20190920201307.500"><vh>@item help-for-&amp;python</vh></v>
<v t="iggu.20190920201307.501"><vh>@item help-for-&amp;scripting</vh></v>
<v t="iggu.20190920201307.502"><vh>@item help-for-&amp;regular-expressions</vh></v>
<v t="iggu.20190920201307.503"><vh>@item help-for-&amp;settings</vh></v>
</v>
<v t="iggu.20190920201307.504"><vh>@menu &amp;Open Tutorial Outlines</vh>
<v t="iggu.20190920201307.505"><vh>@item &amp;open-cheat-sheet-leo</vh></v>
<v t="iggu.20190920201307.506"><vh>@item &amp;open-leo-docs-leo</vh></v>
<v t="iggu.20190920201307.507"><vh>@item &amp;open-quickstart-leo</vh></v>
</v>
<v t="iggu.20190920201307.508"><vh>@menu &amp;Open Web Pages</vh>
<v t="iggu.20190920201307.509"><vh>@item &amp;open-online-home</vh></v>
<v t="iggu.20190920201307.510"><vh>@item &amp;open-online-toc</vh></v>
<v t="iggu.20190920201307.511"><vh>@item &amp;open-users-guide</vh></v>
<v t="iggu.20190920201307.512"><vh>@item &amp;open-online-tutorials</vh></v>
<v t="iggu.20190920201307.513"><vh>@item &amp;open-online-videos</vh></v>
</v>
</v>
</v>
<v t="iggu.20220405122317.1"><vh>@button gitk</vh></v>
<v t="iggu.20191205122008.1"><vh>@bool use-pygments = False</vh></v>
<v t="iggu.20201107154858.1"><vh>@bool use_gutter = True</vh></v>
<v t="iggu.20191205123014.1"><vh>@bool qt-use-scintilla = False</vh></v>
<v t="iggu.20190620194931.1"><vh>@string central-dock-widget = body</vh></v>
<v t="iggu.20190815164817.1"><vh>@bool dockable-log-tabs = True</vh></v>
<v t="iggu.20190620191620.1"><vh>@string theme-name = BreezeDarkTheme_</vh></v>
<v t="iggu.20190815095440.1"><vh>@bool show-tips = False</vh></v>
<v t="iggu.20191106001909.1"><vh>abbrevs</vh>
<v t="iggu.20191106001801.1"><vh>@bool enable-abbreviations = True</vh></v>
<v t="iggu.20191106001906.1"><vh>@bool scripting-abbreviations = True</vh></v>
<v t="iggu.20191106001931.1"><vh>@data abbreviations</vh></v>
</v>
<v t="iggu.20190619190259.2"><vh>@enabled-plugins</vh></v>
<v t="iggu.20190620180104.1"><vh>vim mode</vh>
<v t="iggu.20190620180104.2"><vh>@bool vim-mode = False</vh></v>
<v t="iggu.20190620180104.3"><vh>@bool vim-crosses-lines = True</vh></v>
<v t="iggu.20190624122239.1"><vh>borders</vh>
<v t="iggu.20190620180104.4"><vh>@string vimmodeinsertborder = 1px solid red</vh></v>
<v t="iggu.20190620180104.5"><vh>@string vimmodenormalborder = 1px solid blue</vh></v>
<v t="iggu.20190620180104.6"><vh>@string vimmodevisualborder = 1px solid green</vh></v>
<v t="iggu.20190624103543.1"><vh>@string vim-mode-normal-border = border: 1px solid white</vh></v>
<v t="iggu.20190624103551.1"><vh>@string vim-mode-insert-border = border: 0px solid red</vh></v>
<v t="iggu.20190624103600.1"><vh>@string vim-mode-visual-border = border: 1px solid yellow</vh></v>
</v>
</v>
<v t="iggu.20190920170619.1"><vh>@keys iGGu bindings</vh>
<v t="iggu.20190920170619.4"><vh>@shortcuts Arrow keys and the &lt;return&gt; key</vh></v>
<v t="iggu.20190920170619.5"><vh>@shortcuts Changes</vh></v>
<v t="iggu.20190920170619.6"><vh>@shortcuts Cursor Moves</vh></v>
<v t="iggu.20190920170619.7"><vh>@shortcuts Default plugins</vh></v>
<v t="iggu.20190920170619.8"><vh>@shortcuts Duplicate bindings for Qt</vh></v>
<v t="iggu.20190920170619.9"><vh>@shortcuts F-Keys</vh></v>
<v t="iggu.20190920170619.10"><vh>@shortcuts File commands</vh></v>
<v t="iggu.20190920170619.11"><vh>@shortcuts Find commands</vh></v>
<v t="iggu.20190920170619.12"><vh>@shortcuts Gui operations</vh></v>
<v t="iggu.20190920170619.13"><vh>@shortcuts IPython commands</vh></v>
<v t="iggu.20190920170619.14"><vh>@shortcuts Menu commands</vh></v>
<v t="iggu.20190920170619.15"><vh>@shortcuts Minibuffer commands</vh></v>
<v t="iggu.20190920170619.16"><vh>@shortcuts Other commands</vh></v>
<v t="iggu.20190920170619.17"><vh>@shortcuts Outline operations</vh></v>
<v t="iggu.20190920170619.18"><vh>@shortcuts Plugin-related commands </vh></v>
<v t="iggu.20190920170619.19"><vh>@shortcuts Text operations</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="iggu.20190619190259.1">@language python
</t>
<t tx="iggu.20190619190259.2"># Leo loads plugins in the order they appear here.

# This node *MUST* be a child of the @settings node to take effect.

# **Important**: to change these defaults, put
# an @enabled-plugins node in myLeoSettings.leo.

# Highly-recommended plugins:

plugins_menu.py
free_layout.py
    # Now loaded automatically.
    # But it's useful to have a free_layout menu in the Plugins menu.

# Recommended plugins:

contextmenu.py
    # This is required by the vim.py and xemacs.py plugins.
leo_to_html.py
livecode.py
mod_scripting.py
nav_qt.py
# nodetags.py
quicksearch.py
# python_terminal.py
    # #1009: python_terminal can segfault.
#screen_capture.py
settings_finder.py
stickynotes.py
# todo.py
viewrendered.py

# Alphabetical list of all Leo plugins.

# Note: This list may be out of date. leo/plugins contains all official plugins.
# Note: Leo loads all qt_*.py files automatically when the qt gui is in effect.

# active_path.py
# add_directives.py
# at_folder.py
# at_produce.py
# at_view.py
# attrib_edit.py
# backlink.py
# bibtex.py
# bigdash.py
# bookmarks.py
# bzr_qcommands.py
# chapter_hoist.py
# codewisecompleter.py
# colorize_headlines.py
# contextmenu.py
# ctagscompleter.py
# cursesGui.py
# datenodes.py
# debugger_pudb.py
# dragdropgoodies.py
# dtest.py
# dump_globals.py
# empty_leo_file.py
# enable_gc.py
# expfolder.py
# FileActions.py
# free_layout.py
    # loaded automatically
# ftp.py
# geotag.py
# gitarchive.py
# graphcanvas.py
# import_cisco_config.py
# initinclass.py
# interact.py
# jinjarender.py
# leo_interface.py
# leo_pdf.py
# leo_to_html.py
# leo_to_rtf.py
# leocursor.py
# leofeeds.py
# leomail.py
# leomylyn.py
# leoOPML.py
# leoremote.py
# leoscreen.py
lineNumbers.py
# livecode.py
# macros.py
# markup_inline.py
# maximizeNewWindows.py
# mime.py
# mnplugins.py
# mod_autosave.py
# mod_framesize.py
# mod_http.py
# mod_leo2ascd.py
# mod_read_dir_outline.py
# mod_scripting.py
# mod_speedups.py
# mod_tempfname.py
# mod_timestamp.py
# multifile.py
# nav_qt.py
# nested_splitter.py
    # loaded automatically.
# niceNosent.py
# nodeActions.py
# nodediff.py
# nodetags.py
# nodewatch.py
# notebook.py
# open_shell.py
# outline_export.py
# paste_as_headlines.py
# plugins_menu.py
# pretty_print.py
# projectwizard.py
# python_terminal.py
# QNCalendarWidget.py
# qt_quicksearch.py
# quickMove.py
# quicksearch.py
# quit_leo.py
# read_only_nodes.py
# redirect_to_log.py
# richtext.py
# rss.py
# rst3.py
# run_nodes.py
# screen_capture.py
# screencast.py
# screenshots.py
# script_io_to_body.py
# scripts_menu.py
# setHomeDirectory.py
# settings_finder.py
# sftp.py
# slideshow.py
# spydershell.py
# startfile.py
# stickynotes.py
# stickynotes_plus.py
# systray.py
# testRegisterCommand.py
# textnode.py
# todo.py
# tomboy_import.py
# trace_gc_plugin.py
# trace_keys.py
# trace_tags.py
# valuespace.py
# viewrendered.py
# viewrendered2.py
# vim.py
# wikiview.py
# word_count.py
# word_export.py
# xemacs.py
# xml_edit.py
# xsltWithNodes.py
# zenity_file_dialogs.py
</t>
<t tx="iggu.20190620180104.1"></t>
<t tx="iggu.20190620180104.2"></t>
<t tx="iggu.20190620180104.3"></t>
<t tx="iggu.20190620180104.4"></t>
<t tx="iggu.20190620180104.5"></t>
<t tx="iggu.20190620180104.6"></t>
<t tx="iggu.20190620191620.1">also available:
    LeoBlackSolarized_</t>
<t tx="iggu.20190620194931.1">Setting it to 'body' also makes 'Render' pane manageable.</t>
<t tx="iggu.20190624103543.1"></t>
<t tx="iggu.20190624103551.1"></t>
<t tx="iggu.20190624103600.1"></t>
<t tx="iggu.20190624122239.1"></t>
<t tx="iggu.20190815095440.1"></t>
<t tx="iggu.20190815164817.1"></t>
<t tx="iggu.20190920170619.1">These bindings are a mixture of emacs bindings, windows bindings and vim bindings.</t>
<t tx="iggu.20190920170619.10">close-window                = Ctrl-F4   # (was Alt-F4) Fixes bug 824087: Alt-F4 is not the same as Alt-F, c
exit-leo                    = Ctrl-q
new                         = Ctrl-n    # Ctrl-n conflicts with next-line.
open-outline                = Ctrl-o
save-file                   = Ctrl-s
write-at-file-nodes         = Shift-Ctrl-W
write-dirty-at-file-nodes   = Shift-Ctrl-Q
</t>
<t tx="iggu.20190920170619.11"># Quick finds
backward-find-character                     = Alt-Q
backward-find-character-extend-selection    = Alt-Shift-Q
find-character                              = Alt-P
find-character-extend-selection             = Alt-Shift-P

# To start finds and changes...
start-search                        = Ctrl-f
set-replace-string                  = Ctrl-Shift-r
find-tab-hide                       = None
find-tab-open                       = None

clone-find-all                      = None
isearch-backward                    = Alt-R
isearch-backward-regexp             = None
isearch-forward                     = Alt-I # Alt-S conflicts with &amp;Search and &amp;Settings menus.
isearch-forward-regexp              = None
search-backward                     = None
search-forward                      = None
search-return-to-origin             = None
word-search-backward                = None
word-search-forward                 = None

# To coninue finds and changes...
find-next                           = F3
find-all                            = None
find-prev                           = F2
replace                              = Ctrl-=
replace-all                         = None  # Not recommended to bind this to a shortcut.
replace-then-find                   = Ctrl--

set-find-everywhere                 = Alt-Ctrl-e
set-find-node-only                  = Alt-Ctrl-n
set-find-suboutline-only            = Alt-Ctrl-s
toggle-find-ignore-case-option      = Alt-Ctrl-i
toggle-find-in-body-option          = Alt-Ctrl-b
toggle-find-in-headline-option      = Alt-Ctrl-h
toggle-find-mark-changes-option     = Alt-Ctrl-c
toggle-find-mark-finds-option       = Alt-Ctrl-f
toggle-find-regex-option            = Alt-Ctrl-x
toggle-find-word-option             = Alt-Ctrl-w
toggle-find-wrap-around-option      = Alt-Ctrl-a

search-return-to-origin             = Alt+F3</t>
<t tx="iggu.20190920170619.12"># contract-pane       = Alt-Ctrl--
# expand-pane         = Alt-Ctrl-=
focus-to-body       = Alt-d
focus-to-tree       = Alt-t
toggle-active-pane  = Ctrl-t
keyboard-quit       = Ctrl-g

tab-cycle-previous  = Ctrl-Prior
tab-cycle-next      = Ctrl-Next
tab-cycle-next      = Ctrl-Tab

# Possible alternatives.
# keyboard-quit     = Escape # Hard to type, interferes with dismissing dialogs.
# focus-to-tree     = Ctrl-T
edit-setting        = Ctrl+Key-0
</t>
<t tx="iggu.20190920170619.13"># For testing only.

start-ipython           = Alt-Ctrl-Shift-i
push-to-ipython         = Alt-Shift-i # Alt-i is now bind to isearch-forward.
</t>
<t tx="iggu.20190920170619.14"># These commands do nothing except serve as placeholders for the show-bindings command.
# menu-shortcut = Alt-C # Cmds menu.
# menu-shortcut = Alt-E # Edit menu.
# menu-shortcut = Alt-F # File menu.
# menu-shortcut = Alt-H # Help menu.
# menu-shortcut = Alt-O # Outline menu.
# menu-shortcut = Alt-P # Plugins menu.
# menu-shortcut = Alt-S # Search and Settings menus.
# menu-shortcut = Alt-W # Window menu.
</t>
<t tx="iggu.20190920170619.15">full-command            = Alt-x
# negative-argument     = None      # Alt-minus conflicts with contract-all.
repeat-complex-command  = Ctrl-P
# universal-argument    = Alt-u   # Usually Ctrl-u, conflicts with move-outline-up.



</t>
<t tx="iggu.20190920170619.16">auto-complete-force         = Ctrl-space
auto-complete               = period
goto-prev-history-node      = Ctrl-3
goto-next-history-node      = Ctrl-4
goto-prev-marked      = Ctrl-1
goto-next-marked      = Ctrl-2
debug                       = None
dabbrev-completion          = Alt-Ctrl-slash
dabbrev-expands             = Alt-slash
edit-setting                = None
execute-script              = Ctrl-B
redo                        = Shift-Ctrl-Z
run-all-unit-tests-externally       = None
run-all-unit-tests-locally          = None
run-marked-unit-tests-externally    = None
run-marked-unit-tests-locally       = None
run-selected-unit-tests-externally  = None
run-selected-unit-tests-locally     = None
show-calltips               = parenleft
show-calltips-force         = None # This command needs work before it is useful. Alt-parenleft
sort-siblings               = Alt-A
toggle-autocompleter        = Alt-1
toggle-calltips             = Alt-2
toggle-extend-mode          = Alt-3
undo                        = Ctrl-Z</t>
<t tx="iggu.20190920170619.17">clone-node                  = Ctrl-`
chapter-select              = None
contract-node               = None
copy-node                   = Shift-Ctrl-c
cut-node                    = Shift-Ctrl-x
contract-all                = Alt--
edit-headline               = Ctrl-h
delete-node                 !tree = Delete
delete-node                 !tree = Keypad+Delete
delete-node                 !tree = BackSpace
demote                      = Ctrl-}
demote                      = Ctrl-]
expand-next-level           = None
expand-node                 = Alt-]
extract                     = Shift-Ctrl-D
extract-names               = Shift-Ctrl-N
goto-next-clone             = Alt-N
insert-child                = Ctrl-Insert
insert-node                 = Ctrl-I
insert-node                 !tree = Insert
insert-node                 = Shift-Insert
mark                        = Ctrl-M
move-outline-down           = Ctrl-D
move-outline-left           = Ctrl-L
move-outline-right          = Ctrl-R
move-outline-up             = Ctrl-U
paste-node                  = Shift-Ctrl-V
promote                     = Ctrl-{
promote                     = Ctrl-[</t>
<t tx="iggu.20190920170619.18">find-quick-selected = Ctrl-Shift-F
vr-toggle = Alt-0</t>
<t tx="iggu.20190920170619.19">add-comments                        = Ctrl-parenleft
backward-delete-char                !text = BackSpace
backward-delete-char                = Shift-BackSpace
backward-delete-word-smart          = Ctrl-BackSpace
backward-kill-word                  = Alt-BackSpace
copy-text                           = Ctrl-c        # Conflicts with Emacs ctrl-c
cut-text                            = Ctrl-x
delete-char                         = Shift-Delete
delete-char                         = Keypad+Shift+Delete
delete-char                         !text = Delete
delete-char                         !text = Keypad+Delete
delete-comments                     = Ctrl-* #parenright # Shift-Ctrl-0
delete-word-smart                   = Ctrl-Delete
delete-word-smart                   = Keypad+Ctrl+Delete
delete-spaces                       = None
indent-region                       !text = Tab
indent-region                       = ctrl-greater # Ctrl-shift-&gt;
kill-line                           = Ctrl-;
kill-to-end-of-line                 = Ctrl-k
newline-and-indent                  = Ctrl-j
#newline-and-indent                  !text = Tab
focus-to-body                       !tree = Tab
paste-text                          = Ctrl-v
reformat-paragraph                  = Shift-Ctrl-p
split-line                          = None
unformat-paragraph                  = Shift-Ctrl-u
unindent-region                     = ctrl-less # Ctrl-Shift-&lt;
unindent-region                     = Shift-tab # Only when text is selected.
yank                                = Ctrl-Y
yank-pop                            = Alt-Y
zap-to-character                    = Alt-z</t>
<t tx="iggu.20190920170619.4"># Now that we know what commands are single-line editing commands,
# Only &lt;return&gt; and arrow keys need per-pane bindings.

# These all cause problems on Ubuntu...

# do-nothing    = Ctrl-PageUp  # 20130210 - TNB - defined for tab-flipping,
# do-nothing    = Ctrl-PageDn  # working in Xfce at least

end-edit-headline           ! tree = Return # Escape is also possible.
# end-edit-headline           ! tree = Escape # May interfere with dismissing dialogs.
insert-newline              ! body = Return
insert-newline              ! text = Insert
#
# Keypad variants...
end-edit-headline           ! tree = Keypad+Return
insert-newline              ! body = Keypad+Return

back-char                   ! text = LtArrow
forward-char                ! text = RtArrow
next-line                   ! text = DnArrow
previous-line               ! text = UpArrow
#
# Keypad variants...
back-char                   ! text = Keypad+LtArrow
forward-char                ! text = Keypad+RtArrow
next-line                   ! text = Keypad+DnArrow
previous-line               ! text = Keypad+UpArrow

back-char-extend-selection      ! text = Shift-LtArrow
forward-char-extend-selection   ! text = Shift-RtArrow
next-line-extend-selection      ! text = Shift-DnArrow
previous-line-extend-selection  ! text = Shift-UpArrow
#
# Keypad variants...
back-char-extend-selection      ! text = Keypad+Shift-LtArrow
forward-char-extend-selection   ! text = Keypad+Shift-RtArrow
next-line-extend-selection      ! text = Keypad+Shift-DnArrow
previous-line-extend-selection  ! text = Keypad+Shift-UpArrow

contract-or-go-left         ! tree = LtArrow
expand-and-go-right         ! tree = RtArrow
goto-next-visible           ! tree = DnArrow
goto-prev-visible           ! tree = UpArrow
move-outline-down           ! tree = Shift-DnArrow
move-outline-left           ! tree = Shift-LtArrow
move-outline-right          ! tree = Shift-RtArrow
move-outline-up             ! tree = Shift-UpArrow
#
# Keypad variants...
contract-or-go-left         ! tree = Keypad+LtArrow
expand-and-go-right         ! tree = Keypad+RtArrow
goto-next-visible           ! tree = Keypad+DnArrow
goto-prev-visible           ! tree = Keypad+UpArrow
move-outline-down           ! tree = Keypad+Shift-DnArrow
move-outline-left           ! tree = Keypad+Shift-LtArrow
move-outline-right          ! tree = Keypad+Shift-RtArrow
move-outline-up             ! tree = Keypad+Shift-UpArrow
#
# These cause problems with editing headlines.
# goto-first-visible-node     ! tree= Home
# goto-last-visible-node      ! tree= End
contract-or-go-left         = Alt-LtArrow
expand-and-go-right         = Alt-RtArrow
goto-next-visible           = Alt-DnArrow
goto-prev-visible           = Alt-UpArrow
move-outline-down           = Alt-Shift-DnArrow
move-outline-left           = Alt-Shift-LtArrow
move-outline-right          = Alt-Shift-RtArrow
move-outline-up             = Alt-Shift-UpArrow
#
# Keypad variants...
contract-or-go-left         = Keypad+Alt-LtArrow
expand-and-go-right         = Keypad+Alt-RtArrow
goto-next-visible           = Keypad+Alt-DnArrow
goto-prev-visible           = Keypad+Alt-UpArrow
move-outline-down           = Keypad+Alt-Shift-DnArrow
move-outline-left           = Keypad+Alt-Shift-LtArrow
move-outline-right          = Keypad+Alt-Shift-RtArrow
move-outline-up             = Keypad+Alt-Shift-UpArrow

do-nothing                  ! tree = Ctrl-DnArrow
do-nothing                  ! tree = Ctrl-UpArrow
move-lines-up               ! body = Ctrl-UpArrow
move-lines-down             ! body = Ctrl-DnArrow
#
# Keypad variants...
do-nothing                  ! tree = Keypad+Ctrl-DnArrow
do-nothing                  ! tree = Keypad+Ctrl-UpArrow
move-lines-up               ! body = Keypad+Ctrl-UpArrow
move-lines-down             ! body = Keypad+Ctrl-DnArrow

goto-first-visible-node     = Alt-Home
goto-last-sibling           = Alt-End
#
# Keypad variants...
goto-first-visible-node     = Keypad+Alt-Home
goto-last-sibling           = Keypad+Alt-End

back-page                       ! text = PageUp
back-page-extend-selection      ! text = Shift-PageUp
forward-page                    ! text = PageDn
forward-page-extend-selection   ! text = Shift-PageDn
#
# Keypad variants...
back-page                       ! text = Keypad+PageUp
back-page-extend-selection      ! text = Keypad+Shift-PageUp
forward-page                    ! text = Keypad-PageDn
forward-page-extend-selection   ! text = Keypad+Shift-PageDn

scroll-down-half-page   ! tree = Shift-PageDn
scroll-down-page        ! tree = PageDn
scroll-up-half-page     ! tree = Shift-PageUp
scroll-up-page          ! tree = PageUp
#
# Keypad variants...
scroll-down-half-page   ! tree = Keypad+Shift-PageDn
scroll-down-page        ! tree = Keypad+PageDn
scroll-up-half-page     ! tree = Keypad+Shift-PageUp
scroll-up-page          ! tree = Keypad+PageUp
</t>
<t tx="iggu.20190920170619.5"># cycle-focus                       = None
# cycle-all-focus                   = Ctrl-Shift-tab

back-word-smart                     = Ctrl-LtArrow
back-word-smart-extend-selection    = Ctrl-Shift-LtArrow
beginning-of-buffer                 = Ctrl-Home
beginning-of-buffer-extend-selection= Ctrl-Shift-Home
end-of-buffer                       = Ctrl-End
end-of-buffer-extend-selection      = Ctrl-Shift-End
forward-word-smart                  = Ctrl-RtArrow
forward-word-smart-extend-selection = Ctrl-Shift-RtArrow
#
# Keypad variants...
back-word-smart                     = Keypad+Ctrl-LtArrow
back-word-smart-extend-selection    = Keypad+Ctrl-Shift-LtArrow
beginning-of-buffer                 = Keypad+Ctrl-Home
beginning-of-buffer-extend-selection= Keypad+Ctrl-Shift-Home
end-of-buffer                       = Keypad+Ctrl-End
end-of-buffer-extend-selection      = Keypad+Ctrl-Shift-End
forward-word-smart                  = Keypad+Ctrl-RtArrow
forward-word-smart-extend-selection = Keypad+Ctrl-Shift-RtArrow

# beginning-of-line                   = Home
back-to-home                        = Home
beginning-of-line-extend-selection  = Shift-Home
end-of-line                         = End
end-of-line-extend-selection        = Shift-End
#
# Keypad variants...
back-to-home                        = Keypad+Home
beginning-of-line-extend-selection  = Keypad+Shift-Home
end-of-line                         = Keypad+End
end-of-line-extend-selection        = Keypad+Shift-End

match-brackets                      = Ctrl-%
</t>
<t tx="iggu.20190920170619.6"># Important: arrow keys also move the cursor: all arrow keys are handled elsewhere.

back-word-smart                     = None # Alt-b
back-word-smart-extend-selection    = None # Alt-Shift-b
back-to-indentation                 = None # Ctrl-space
beginning-of-line                   = None # Ctrl-a
beginning-of-line-extend-selection  = Ctrl-Shift-a
end-of-line                         = Ctrl-e
exchange-point-mark                 = Alt-M     # Should be Ctrl-X Ctrl-X.
end-of-line-extend-selection        = Ctrl-Shift-e
extend-to-line                      = Alt-L
extend-to-word                      = Ctrl-W # Alt-W
forward-paragraph                   = Alt-}
forward-paragraph-extend-selection  = Alt-Ctrl-}
forward-sentence                    = Alt-e
forward-sentence-extend-selection   = Alt-Shift-e
forward-word-smart                  = None # Alt-f
forward-word-smart-extend-selection = None # Alt-Shift-f
goto-global-line                    = Alt-g
# match-brackets                    = Ctrl-K    # kill-line
move-past-close                     = Alt-parenright # Same as Alt-shift-parenright
move-past-close-extend-selection    = None
# next-line                         = Ctrl-N
# next-line-extend-selection        = Ctrl-Shift-N
# previous-line                     = Ctrl-P
# previous-line-extend-selection    = Ctrl-Shift-P
select-all                          = Ctrl-a</t>
<t tx="iggu.20190920170619.7"># Open current node in external editor. 'v' is mnemonic for 'vi', because vi users request this most
# cm-external-editor = Alt-v</t>
<t tx="iggu.20190920170619.8"># These are needed because Qt reports Ctrl-( as Ctrl-Shift-9, etc.

# add-comments        = Ctrl-Shift-9  # Ctrl-parenleft
# delete-comments     = Ctrl-Shift-0  # Ctrl-parenright
# demote              = Ctrl-Shift-]  # Ctrl-}
# move-past-close     = Alt-Shift-0   # Alt-parenright
# promote             = Ctrl-Shift-[  # Ctrl-{
</t>
<t tx="iggu.20190920170619.9"># Unbound F-Keys cause problems on Ubuntu
help            = F1
# find-prev     = F2    # Set elsewhere
# find-next     = F3    # Set elsewhere
rstrip-node     = F4
do-nothing      = F5
do-nothing      = F6
spell-tab-open  = F7
do-nothing      = F8
do-nothing      = F9
do-nothing      = F10
help-for-command= F11
help-for-python = F12

do-nothing              = Ctrl-F1
do-nothing              = Ctrl-F2
double-click-icon-box   = Ctrl-F3
# close-window          = Ctrl-F4 # Set in File Commands.
do-nothing              = Ctrl-F5
do-nothing              = Ctrl-F6
do-nothing              = Ctrl-F7
do-nothing              = Ctrl-F8
do-nothing              = Ctrl-F9
do-nothing              = Ctrl-F10
do-nothing              = Ctrl-F11
do-nothing              = Ctrl-F12

do-nothing = Shift-F1
do-nothing = Shift-F2
do-nothing = Shift-F3
do-nothing = Shift-F4
do-nothing = Shift-F5
do-nothing = Shift-F6
do-nothing = Shift-F7
do-nothing = Shift-F8
do-nothing = Shift-F9
do-nothing = Shift-F10
do-nothing = Shift-F11
do-nothing = Shift-F12</t>
<t tx="iggu.20190920201307.1">@language md

This is copied from leoSettings.leo file to get rid of toplevel menu's shorcuts
-------------------------------------------------------------------------------

https://groups.google.com/d/msg/leo-editor/C5yNr0UqzpA/jtov-76eBQAJ

You can try a custom menu.
Open leoSettings.leo and navigate to the main @menu node.
Copy this node and paste it into your myLeoSettings.leo under the @settings node.
Change the top level headlines to lose the hotkey markers.
The downside is remembering to update your @menu node every now and then so you don't miss out on new features. :-)</t>
<t tx="iggu.20190920201307.10">&amp;CheatSheet.leo</t>
<t tx="iggu.20190920201307.100"></t>
<t tx="iggu.20190920201307.101"></t>
<t tx="iggu.20190920201307.102"></t>
<t tx="iggu.20190920201307.103"></t>
<t tx="iggu.20190920201307.104"></t>
<t tx="iggu.20190920201307.105">&amp;Refresh From Disk</t>
<t tx="iggu.20190920201307.106">&amp;Revert To Saved</t>
<t tx="iggu.20190920201307.107"></t>
<t tx="iggu.20190920201307.108">E&amp;xit</t>
<t tx="iggu.20190920201307.109"></t>
<t tx="iggu.20190920201307.11">Leo&amp;Docs.leo</t>
<t tx="iggu.20190920201307.110">Can't Undo</t>
<t tx="iggu.20190920201307.111">Can't Redo</t>
<t tx="iggu.20190920201307.112"></t>
<t tx="iggu.20190920201307.113">Cu&amp;t</t>
<t tx="iggu.20190920201307.114">Cop&amp;y</t>
<t tx="iggu.20190920201307.115">&amp;Paste</t>
<t tx="iggu.20190920201307.116">Select &amp;All</t>
<t tx="iggu.20190920201307.117"></t>
<t tx="iggu.20190920201307.118"></t>
<t tx="iggu.20190920201307.119"></t>
<t tx="iggu.20190920201307.12">Leo&amp;Dist.leo</t>
<t tx="iggu.20190920201307.120"></t>
<t tx="iggu.20190920201307.121"></t>
<t tx="iggu.20190920201307.122"></t>
<t tx="iggu.20190920201307.123"></t>
<t tx="iggu.20190920201307.124"></t>
<t tx="iggu.20190920201307.125"></t>
<t tx="iggu.20190920201307.126"></t>
<t tx="iggu.20190920201307.127"></t>
<t tx="iggu.20190920201307.128"></t>
<t tx="iggu.20190920201307.129"></t>
<t tx="iggu.20190920201307.13">leo&amp;Plugins.leo</t>
<t tx="iggu.20190920201307.130"></t>
<t tx="iggu.20190920201307.131"></t>
<t tx="iggu.20190920201307.132"></t>
<t tx="iggu.20190920201307.133"></t>
<t tx="iggu.20190920201307.134"></t>
<t tx="iggu.20190920201307.135"></t>
<t tx="iggu.20190920201307.136"></t>
<t tx="iggu.20190920201307.137"></t>
<t tx="iggu.20190920201307.138"></t>
<t tx="iggu.20190920201307.139"></t>
<t tx="iggu.20190920201307.14">leoP&amp;y.leo</t>
<t tx="iggu.20190920201307.140"></t>
<t tx="iggu.20190920201307.141"></t>
<t tx="iggu.20190920201307.142"></t>
<t tx="iggu.20190920201307.143"></t>
<t tx="iggu.20190920201307.144"></t>
<t tx="iggu.20190920201307.145"></t>
<t tx="iggu.20190920201307.146"></t>
<t tx="iggu.20190920201307.147"></t>
<t tx="iggu.20190920201307.148"></t>
<t tx="iggu.20190920201307.149"></t>
<t tx="iggu.20190920201307.15">&amp;myLeoSettings.leo
</t>
<t tx="iggu.20190920201307.150"></t>
<t tx="iggu.20190920201307.151"></t>
<t tx="iggu.20190920201307.152"></t>
<t tx="iggu.20190920201307.153">Show In&amp;visibles</t>
<t tx="iggu.20190920201307.154"></t>
<t tx="iggu.20190920201307.155"></t>
<t tx="iggu.20190920201307.156"></t>
<t tx="iggu.20190920201307.157"></t>
<t tx="iggu.20190920201307.158"></t>
<t tx="iggu.20190920201307.159"></t>
<t tx="iggu.20190920201307.16">&amp;quickstart.leo</t>
<t tx="iggu.20190920201307.160"></t>
<t tx="iggu.20190920201307.161"></t>
<t tx="iggu.20190920201307.162"></t>
<t tx="iggu.20190920201307.163"></t>
<t tx="iggu.20190920201307.164"></t>
<t tx="iggu.20190920201307.165"></t>
<t tx="iggu.20190920201307.166"></t>
<t tx="iggu.20190920201307.167"></t>
<t tx="iggu.20190920201307.168"></t>
<t tx="iggu.20190920201307.169"></t>
<t tx="iggu.20190920201307.17">scr&amp;ipts.leo</t>
<t tx="iggu.20190920201307.170"></t>
<t tx="iggu.20190920201307.171"></t>
<t tx="iggu.20190920201307.172"></t>
<t tx="iggu.20190920201307.173"></t>
<t tx="iggu.20190920201307.174"></t>
<t tx="iggu.20190920201307.175"></t>
<t tx="iggu.20190920201307.176"></t>
<t tx="iggu.20190920201307.177"></t>
<t tx="iggu.20190920201307.178"></t>
<t tx="iggu.20190920201307.179"></t>
<t tx="iggu.20190920201307.18">leo&amp;Settings.leo</t>
<t tx="iggu.20190920201307.180"></t>
<t tx="iggu.20190920201307.181"></t>
<t tx="iggu.20190920201307.182"></t>
<t tx="iggu.20190920201307.183"></t>
<t tx="iggu.20190920201307.184"></t>
<t tx="iggu.20190920201307.185"></t>
<t tx="iggu.20190920201307.186"></t>
<t tx="iggu.20190920201307.187"></t>
<t tx="iggu.20190920201307.188"></t>
<t tx="iggu.20190920201307.189"></t>
<t tx="iggu.20190920201307.19">&amp;unittest.leo</t>
<t tx="iggu.20190920201307.190"></t>
<t tx="iggu.20190920201307.191"></t>
<t tx="iggu.20190920201307.192"></t>
<t tx="iggu.20190920201307.193"></t>
<t tx="iggu.20190920201307.194"></t>
<t tx="iggu.20190920201307.195"></t>
<t tx="iggu.20190920201307.196"></t>
<t tx="iggu.20190920201307.197"></t>
<t tx="iggu.20190920201307.198"></t>
<t tx="iggu.20190920201307.199"></t>
<t tx="iggu.20190920201307.2"></t>
<t tx="iggu.20190920201307.20"># 文件
# The first non-blank, non-comment body line is an alternate menu name.
#
# A placeholder for the actual menu.
# Leo's init code populates this menu as a special case.</t>
<t tx="iggu.20190920201307.200"></t>
<t tx="iggu.20190920201307.201"></t>
<t tx="iggu.20190920201307.202"></t>
<t tx="iggu.20190920201307.203"></t>
<t tx="iggu.20190920201307.204"></t>
<t tx="iggu.20190920201307.205"></t>
<t tx="iggu.20190920201307.206"></t>
<t tx="iggu.20190920201307.207"></t>
<t tx="iggu.20190920201307.208"></t>
<t tx="iggu.20190920201307.209"></t>
<t tx="iggu.20190920201307.21"></t>
<t tx="iggu.20190920201307.210"></t>
<t tx="iggu.20190920201307.211"></t>
<t tx="iggu.20190920201307.212"></t>
<t tx="iggu.20190920201307.213"></t>
<t tx="iggu.20190920201307.214"></t>
<t tx="iggu.20190920201307.215"></t>
<t tx="iggu.20190920201307.216"></t>
<t tx="iggu.20190920201307.217"></t>
<t tx="iggu.20190920201307.218"></t>
<t tx="iggu.20190920201307.219"></t>
<t tx="iggu.20190920201307.22">&amp;Save...</t>
<t tx="iggu.20190920201307.220"></t>
<t tx="iggu.20190920201307.221"></t>
<t tx="iggu.20190920201307.222"></t>
<t tx="iggu.20190920201307.223"></t>
<t tx="iggu.20190920201307.224"></t>
<t tx="iggu.20190920201307.225"></t>
<t tx="iggu.20190920201307.226"></t>
<t tx="iggu.20190920201307.227"></t>
<t tx="iggu.20190920201307.228"></t>
<t tx="iggu.20190920201307.229"></t>
<t tx="iggu.20190920201307.23">Save &amp;As...</t>
<t tx="iggu.20190920201307.230"></t>
<t tx="iggu.20190920201307.231"></t>
<t tx="iggu.20190920201307.232"></t>
<t tx="iggu.20190920201307.233"></t>
<t tx="iggu.20190920201307.234"></t>
<t tx="iggu.20190920201307.235"></t>
<t tx="iggu.20190920201307.236"></t>
<t tx="iggu.20190920201307.237"></t>
<t tx="iggu.20190920201307.238"></t>
<t tx="iggu.20190920201307.239"></t>
<t tx="iggu.20190920201307.24">Save As &amp;Unzipped...</t>
<t tx="iggu.20190920201307.240"></t>
<t tx="iggu.20190920201307.241"></t>
<t tx="iggu.20190920201307.242"></t>
<t tx="iggu.20190920201307.243"></t>
<t tx="iggu.20190920201307.244"></t>
<t tx="iggu.20190920201307.245"></t>
<t tx="iggu.20190920201307.246"></t>
<t tx="iggu.20190920201307.247"></t>
<t tx="iggu.20190920201307.248"></t>
<t tx="iggu.20190920201307.249"></t>
<t tx="iggu.20190920201307.25">Save As &amp;Zipped...</t>
<t tx="iggu.20190920201307.250"></t>
<t tx="iggu.20190920201307.251"></t>
<t tx="iggu.20190920201307.252"></t>
<t tx="iggu.20190920201307.253"></t>
<t tx="iggu.20190920201307.254"></t>
<t tx="iggu.20190920201307.255"></t>
<t tx="iggu.20190920201307.256"></t>
<t tx="iggu.20190920201307.257"></t>
<t tx="iggu.20190920201307.258"></t>
<t tx="iggu.20190920201307.259"></t>
<t tx="iggu.20190920201307.26">Save &amp;To...</t>
<t tx="iggu.20190920201307.260"></t>
<t tx="iggu.20190920201307.261"></t>
<t tx="iggu.20190920201307.262"></t>
<t tx="iggu.20190920201307.263"># Alt+Ctrl+E set-find-everywhere
# Alt+Ctrl+N set-find-node-only
# Alt+Ctrl+S set-find-suboutline-only
</t>
<t tx="iggu.20190920201307.264"></t>
<t tx="iggu.20190920201307.265"></t>
<t tx="iggu.20190920201307.266"></t>
<t tx="iggu.20190920201307.267"></t>
<t tx="iggu.20190920201307.268"></t>
<t tx="iggu.20190920201307.269"></t>
<t tx="iggu.20190920201307.27"></t>
<t tx="iggu.20190920201307.270"></t>
<t tx="iggu.20190920201307.271"></t>
<t tx="iggu.20190920201307.272"></t>
<t tx="iggu.20190920201307.273"></t>
<t tx="iggu.20190920201307.274"></t>
<t tx="iggu.20190920201307.275"></t>
<t tx="iggu.20190920201307.276"></t>
<t tx="iggu.20190920201307.277"></t>
<t tx="iggu.20190920201307.278"></t>
<t tx="iggu.20190920201307.279"></t>
<t tx="iggu.20190920201307.28"></t>
<t tx="iggu.20190920201307.280"></t>
<t tx="iggu.20190920201307.281"></t>
<t tx="iggu.20190920201307.282"></t>
<t tx="iggu.20190920201307.283"></t>
<t tx="iggu.20190920201307.284"></t>
<t tx="iggu.20190920201307.285">Open &amp;LeoSettings.leo</t>
<t tx="iggu.20190920201307.286">Open &amp;myLeoSettings.leo
</t>
<t tx="iggu.20190920201307.287">Open A &amp;Theme File</t>
<t tx="iggu.20190920201307.288">&amp;Select Local @settings tree</t>
<t tx="iggu.20190920201307.289"></t>
<t tx="iggu.20190920201307.29"></t>
<t tx="iggu.20190920201307.290"></t>
<t tx="iggu.20190920201307.291"></t>
<t tx="iggu.20190920201307.292"></t>
<t tx="iggu.20190920201307.293"></t>
<t tx="iggu.20190920201307.294"></t>
<t tx="iggu.20190920201307.295"></t>
<t tx="iggu.20190920201307.296"></t>
<t tx="iggu.20190920201307.297"></t>
<t tx="iggu.20190920201307.298"></t>
<t tx="iggu.20190920201307.299"></t>
<t tx="iggu.20190920201307.3"></t>
<t tx="iggu.20190920201307.30"></t>
<t tx="iggu.20190920201307.300"></t>
<t tx="iggu.20190920201307.301"></t>
<t tx="iggu.20190920201307.302"></t>
<t tx="iggu.20190920201307.303"></t>
<t tx="iggu.20190920201307.304"></t>
<t tx="iggu.20190920201307.305"></t>
<t tx="iggu.20190920201307.306"></t>
<t tx="iggu.20190920201307.307"></t>
<t tx="iggu.20190920201307.308"></t>
<t tx="iggu.20190920201307.309"></t>
<t tx="iggu.20190920201307.31"></t>
<t tx="iggu.20190920201307.310"></t>
<t tx="iggu.20190920201307.311"></t>
<t tx="iggu.20190920201307.312"></t>
<t tx="iggu.20190920201307.313"></t>
<t tx="iggu.20190920201307.314"></t>
<t tx="iggu.20190920201307.315"></t>
<t tx="iggu.20190920201307.316"></t>
<t tx="iggu.20190920201307.317"></t>
<t tx="iggu.20190920201307.318"></t>
<t tx="iggu.20190920201307.319"></t>
<t tx="iggu.20190920201307.32"></t>
<t tx="iggu.20190920201307.320"></t>
<t tx="iggu.20190920201307.321"></t>
<t tx="iggu.20190920201307.322"></t>
<t tx="iggu.20190920201307.323"></t>
<t tx="iggu.20190920201307.324">Pas&amp;te Node As Clone</t>
<t tx="iggu.20190920201307.325"></t>
<t tx="iggu.20190920201307.326"></t>
<t tx="iggu.20190920201307.327"></t>
<t tx="iggu.20190920201307.328"></t>
<t tx="iggu.20190920201307.329"></t>
<t tx="iggu.20190920201307.33"></t>
<t tx="iggu.20190920201307.330">This node just keeps track of the accelerators in the siblings.</t>
<t tx="iggu.20190920201307.331"></t>
<t tx="iggu.20190920201307.332"></t>
<t tx="iggu.20190920201307.333"></t>
<t tx="iggu.20190920201307.334"></t>
<t tx="iggu.20190920201307.335"></t>
<t tx="iggu.20190920201307.336"></t>
<t tx="iggu.20190920201307.337"></t>
<t tx="iggu.20190920201307.338"></t>
<t tx="iggu.20190920201307.339"></t>
<t tx="iggu.20190920201307.34"></t>
<t tx="iggu.20190920201307.340"></t>
<t tx="iggu.20190920201307.341"></t>
<t tx="iggu.20190920201307.342"></t>
<t tx="iggu.20190920201307.343"></t>
<t tx="iggu.20190920201307.344"></t>
<t tx="iggu.20190920201307.345"></t>
<t tx="iggu.20190920201307.346"></t>
<t tx="iggu.20190920201307.347"></t>
<t tx="iggu.20190920201307.348"></t>
<t tx="iggu.20190920201307.349"></t>
<t tx="iggu.20190920201307.35"></t>
<t tx="iggu.20190920201307.350"></t>
<t tx="iggu.20190920201307.351"></t>
<t tx="iggu.20190920201307.352"></t>
<t tx="iggu.20190920201307.353"></t>
<t tx="iggu.20190920201307.354"></t>
<t tx="iggu.20190920201307.355">Go To &amp;First Node</t>
<t tx="iggu.20190920201307.356">Go To First V&amp;isible</t>
<t tx="iggu.20190920201307.357">Go To First Si&amp;bling</t>
<t tx="iggu.20190920201307.358"></t>
<t tx="iggu.20190920201307.359">Go To Next C&amp;hanged</t>
<t tx="iggu.20190920201307.36"></t>
<t tx="iggu.20190920201307.360">Go To Next &amp;Clone</t>
<t tx="iggu.20190920201307.361">Go To Next &amp;Marked</t>
<t tx="iggu.20190920201307.362">Go To Next N&amp;ode</t>
<t tx="iggu.20190920201307.363">Go To Next &amp;Sibling</t>
<t tx="iggu.20190920201307.364">Go To Next Visibl&amp;e</t>
<t tx="iggu.20190920201307.365">Go To Next Visite&amp;d</t>
<t tx="iggu.20190920201307.366"></t>
<t tx="iggu.20190920201307.367">Go To P&amp;arent</t>
<t tx="iggu.20190920201307.368"></t>
<t tx="iggu.20190920201307.369">Go To &amp;Prev Node</t>
<t tx="iggu.20190920201307.37"></t>
<t tx="iggu.20190920201307.370">Go To P&amp;rev Sibling</t>
<t tx="iggu.20190920201307.371">Go To Pre&amp;v Visible</t>
<t tx="iggu.20190920201307.372">Go To Prev Visi&amp;ted</t>
<t tx="iggu.20190920201307.373"></t>
<t tx="iggu.20190920201307.374">Go To Last Node</t>
<t tx="iggu.20190920201307.375">Go To Last Siblin&amp;g</t>
<t tx="iggu.20190920201307.376">Go To &amp;Last Visible</t>
<t tx="iggu.20190920201307.377"></t>
<t tx="iggu.20190920201307.378"></t>
<t tx="iggu.20190920201307.379">D&amp;e-Hoist</t>
<t tx="iggu.20190920201307.38"></t>
<t tx="iggu.20190920201307.380"></t>
<t tx="iggu.20190920201307.381"></t>
<t tx="iggu.20190920201307.382"></t>
<t tx="iggu.20190920201307.383"></t>
<t tx="iggu.20190920201307.384"></t>
<t tx="iggu.20190920201307.385"></t>
<t tx="iggu.20190920201307.386"></t>
<t tx="iggu.20190920201307.387"></t>
<t tx="iggu.20190920201307.388"></t>
<t tx="iggu.20190920201307.389"></t>
<t tx="iggu.20190920201307.39"></t>
<t tx="iggu.20190920201307.390"></t>
<t tx="iggu.20190920201307.391"></t>
<t tx="iggu.20190920201307.392">Move &amp;Down</t>
<t tx="iggu.20190920201307.393">Move &amp;Left</t>
<t tx="iggu.20190920201307.394">Move &amp;Right</t>
<t tx="iggu.20190920201307.395">Move &amp;Up</t>
<t tx="iggu.20190920201307.396"></t>
<t tx="iggu.20190920201307.397"></t>
<t tx="iggu.20190920201307.398"></t>
<t tx="iggu.20190920201307.399"></t>
<t tx="iggu.20190920201307.4"></t>
<t tx="iggu.20190920201307.40">&amp;Compare Leo Files...</t>
<t tx="iggu.20190920201307.400"></t>
<t tx="iggu.20190920201307.401"></t>
<t tx="iggu.20190920201307.402"></t>
<t tx="iggu.20190920201307.403">Open leo&amp;Plugins.leo</t>
<t tx="iggu.20190920201307.404">Print Plugins &amp;Info</t>
<t tx="iggu.20190920201307.405"></t>
<t tx="iggu.20190920201307.406"></t>
<t tx="iggu.20190920201307.407"></t>
<t tx="iggu.20190920201307.408"></t>
<t tx="iggu.20190920201307.409"></t>
<t tx="iggu.20190920201307.41"></t>
<t tx="iggu.20190920201307.410"></t>
<t tx="iggu.20190920201307.411"></t>
<t tx="iggu.20190920201307.412"></t>
<t tx="iggu.20190920201307.413"></t>
<t tx="iggu.20190920201307.414"></t>
<t tx="iggu.20190920201307.415"></t>
<t tx="iggu.20190920201307.416"></t>
<t tx="iggu.20190920201307.417"></t>
<t tx="iggu.20190920201307.418"></t>
<t tx="iggu.20190920201307.419"></t>
<t tx="iggu.20190920201307.42"></t>
<t tx="iggu.20190920201307.420"></t>
<t tx="iggu.20190920201307.421"></t>
<t tx="iggu.20190920201307.422"></t>
<t tx="iggu.20190920201307.423"></t>
<t tx="iggu.20190920201307.424"></t>
<t tx="iggu.20190920201307.425"></t>
<t tx="iggu.20190920201307.426"></t>
<t tx="iggu.20190920201307.427"></t>
<t tx="iggu.20190920201307.428"></t>
<t tx="iggu.20190920201307.429"></t>
<t tx="iggu.20190920201307.43"></t>
<t tx="iggu.20190920201307.430"></t>
<t tx="iggu.20190920201307.431">Open External &amp;Debugger</t>
<t tx="iggu.20190920201307.432">Open &amp;Pdb Debugger</t>
<t tx="iggu.20190920201307.433"></t>
<t tx="iggu.20190920201307.434"></t>
<t tx="iggu.20190920201307.435"></t>
<t tx="iggu.20190920201307.436"></t>
<t tx="iggu.20190920201307.437"></t>
<t tx="iggu.20190920201307.438"></t>
<t tx="iggu.20190920201307.439"></t>
<t tx="iggu.20190920201307.44">Read @auto Nodes</t>
<t tx="iggu.20190920201307.440"></t>
<t tx="iggu.20190920201307.441"></t>
<t tx="iggu.20190920201307.442"></t>
<t tx="iggu.20190920201307.443"></t>
<t tx="iggu.20190920201307.444"></t>
<t tx="iggu.20190920201307.445"></t>
<t tx="iggu.20190920201307.446"></t>
<t tx="iggu.20190920201307.447"></t>
<t tx="iggu.20190920201307.448"></t>
<t tx="iggu.20190920201307.449"></t>
<t tx="iggu.20190920201307.45">Read @&lt;file&gt; Nodes</t>
<t tx="iggu.20190920201307.450"></t>
<t tx="iggu.20190920201307.451"></t>
<t tx="iggu.20190920201307.452"></t>
<t tx="iggu.20190920201307.453"></t>
<t tx="iggu.20190920201307.454"></t>
<t tx="iggu.20190920201307.455"></t>
<t tx="iggu.20190920201307.456"></t>
<t tx="iggu.20190920201307.457"></t>
<t tx="iggu.20190920201307.458"></t>
<t tx="iggu.20190920201307.459"></t>
<t tx="iggu.20190920201307.46">Read @shadow Nodes</t>
<t tx="iggu.20190920201307.460"></t>
<t tx="iggu.20190920201307.461"></t>
<t tx="iggu.20190920201307.462"></t>
<t tx="iggu.20190920201307.463"></t>
<t tx="iggu.20190920201307.464"></t>
<t tx="iggu.20190920201307.465"></t>
<t tx="iggu.20190920201307.466"></t>
<t tx="iggu.20190920201307.467"></t>
<t tx="iggu.20190920201307.468"></t>
<t tx="iggu.20190920201307.469"></t>
<t tx="iggu.20190920201307.47"></t>
<t tx="iggu.20190920201307.470"></t>
<t tx="iggu.20190920201307.471"></t>
<t tx="iggu.20190920201307.472"></t>
<t tx="iggu.20190920201307.473"></t>
<t tx="iggu.20190920201307.474"></t>
<t tx="iggu.20190920201307.475"></t>
<t tx="iggu.20190920201307.476"></t>
<t tx="iggu.20190920201307.477"></t>
<t tx="iggu.20190920201307.478"></t>
<t tx="iggu.20190920201307.479"></t>
<t tx="iggu.20190920201307.48"></t>
<t tx="iggu.20190920201307.480"></t>
<t tx="iggu.20190920201307.481"></t>
<t tx="iggu.20190920201307.482"></t>
<t tx="iggu.20190920201307.483"></t>
<t tx="iggu.20190920201307.484"></t>
<t tx="iggu.20190920201307.485"></t>
<t tx="iggu.20190920201307.486"></t>
<t tx="iggu.20190920201307.487"></t>
<t tx="iggu.20190920201307.488"></t>
<t tx="iggu.20190920201307.489"></t>
<t tx="iggu.20190920201307.49"></t>
<t tx="iggu.20190920201307.490"></t>
<t tx="iggu.20190920201307.491"></t>
<t tx="iggu.20190920201307.492"></t>
<t tx="iggu.20190920201307.493"></t>
<t tx="iggu.20190920201307.494"></t>
<t tx="iggu.20190920201307.495"></t>
<t tx="iggu.20190920201307.496"></t>
<t tx="iggu.20190920201307.497"></t>
<t tx="iggu.20190920201307.498"></t>
<t tx="iggu.20190920201307.499"></t>
<t tx="iggu.20190920201307.5"></t>
<t tx="iggu.20190920201307.50">Write @auto Nodes</t>
<t tx="iggu.20190920201307.500"></t>
<t tx="iggu.20190920201307.501"></t>
<t tx="iggu.20190920201307.502"></t>
<t tx="iggu.20190920201307.503"></t>
<t tx="iggu.20190920201307.504"></t>
<t tx="iggu.20190920201307.505"></t>
<t tx="iggu.20190920201307.506"></t>
<t tx="iggu.20190920201307.507"></t>
<t tx="iggu.20190920201307.508"></t>
<t tx="iggu.20190920201307.509"></t>
<t tx="iggu.20190920201307.51">Write @&lt;file&gt; Nodes</t>
<t tx="iggu.20190920201307.510"></t>
<t tx="iggu.20190920201307.511"></t>
<t tx="iggu.20190920201307.512">Text &amp;Tutorials</t>
<t tx="iggu.20190920201307.513">&amp;Video Tutorials</t>
<t tx="iggu.20190920201307.52">Write @shadow Nodes</t>
<t tx="iggu.20190920201307.53"></t>
<t tx="iggu.20190920201307.54">Write Dirty @auto Nodes</t>
<t tx="iggu.20190920201307.55">Write Dirty @&lt;file&gt; Nodes</t>
<t tx="iggu.20190920201307.56">Write Dirty @shadow Nodes</t>
<t tx="iggu.20190920201307.57">Write Missing @&lt;file&gt; Nodes</t>
<t tx="iggu.20190920201307.58"></t>
<t tx="iggu.20190920201307.59">Import &amp;Any File...</t>
<t tx="iggu.20190920201307.6"></t>
<t tx="iggu.20190920201307.60">Import &amp;FreeMind Files...</t>
<t tx="iggu.20190920201307.61">Import &amp;MindJet Files...</t>
<t tx="iggu.20190920201307.62">Import M&amp;ORE Files...</t>
<t tx="iggu.20190920201307.63">Import &amp;Jupyter Notebook...</t>
<t tx="iggu.20190920201307.64">Import &amp;Tabbed File...</t>
<t tx="iggu.20190920201307.65">Import &amp;Zim Folder...</t>
<t tx="iggu.20190920201307.66"></t>
<t tx="iggu.20190920201307.67">Export &amp;Outline...</t>
<t tx="iggu.20190920201307.68">Export &amp;Jupyter Notebook</t>
<t tx="iggu.20190920201307.69">&amp;Flatten Selected Outline...</t>
<t tx="iggu.20190920201307.7"></t>
<t tx="iggu.20190920201307.70">Outline To &amp;CWEB...</t>
<t tx="iggu.20190920201307.71">Outline To &amp;Noweb...</t>
<t tx="iggu.20190920201307.72">&amp;Remove Sentinels...</t>
<t tx="iggu.20190920201307.73">&amp;Weave...</t>
<t tx="iggu.20190920201307.74"></t>
<t tx="iggu.20190920201307.75"></t>
<t tx="iggu.20190920201307.76"></t>
<t tx="iggu.20190920201307.77"></t>
<t tx="iggu.20190920201307.78"></t>
<t tx="iggu.20190920201307.79"></t>
<t tx="iggu.20190920201307.8"></t>
<t tx="iggu.20190920201307.80"></t>
<t tx="iggu.20190920201307.81"></t>
<t tx="iggu.20190920201307.82"></t>
<t tx="iggu.20190920201307.83"></t>
<t tx="iggu.20190920201307.84"></t>
<t tx="iggu.20190920201307.85"></t>
<t tx="iggu.20190920201307.86"></t>
<t tx="iggu.20190920201307.87"></t>
<t tx="iggu.20190920201307.88"></t>
<t tx="iggu.20190920201307.89"></t>
<t tx="iggu.20190920201307.9"></t>
<t tx="iggu.20190920201307.90"></t>
<t tx="iggu.20190920201307.91"></t>
<t tx="iggu.20190920201307.92"></t>
<t tx="iggu.20190920201307.93"></t>
<t tx="iggu.20190920201307.94"></t>
<t tx="iggu.20190920201307.95"></t>
<t tx="iggu.20190920201307.96"></t>
<t tx="iggu.20190920201307.97"></t>
<t tx="iggu.20190920201307.98"></t>
<t tx="iggu.20190920201307.99"></t>
<t tx="iggu.20191106001801.1"></t>
<t tx="iggu.20191106001906.1"></t>
<t tx="iggu.20191106001909.1"></t>
<t tx="iggu.20191106001931.1">l-rst;;=@language rst
\:
\:

l-md;;=@language md
\:
\:

l-css;;=@language css
\:
\:

l-js;;=@language javascript
\:
\:

l-html;;=@language html
\:
\:

l-py;;=@language python
\:
\:


ts;;={|{import time ; x=time.strftime("%Y/%m/%d-%H:%M:%S")}|}


c;;=console.

ctrace;;=console.trace(&lt;|what|&gt;);
cdebug;;=console.debug(&lt;|what|&gt;);
cinfo;;=console.info(&lt;|what|&gt;);
cwarn;;=console.warn(&lt;|what|&gt;);
cerr;;=console.error(&lt;|what|&gt;);
cexc;;=console.exception(&lt;|what|&gt;);

clo;;=console.log
clog;;=console.log(&lt;|what|&gt;);

if;;=if (&lt;|cond|&gt;) {
\:    &lt;|body|&gt;
\:}

while;;=while (&lt;|cond|&gt;) {
\:    &lt;|body|&gt;
\:}

for;;=for (&lt;|start|&gt;; &lt;|end|&gt;; &lt;|step|&gt;) {
\:    &lt;|body|&gt;
\:}
</t>
<t tx="iggu.20191119114302.1"></t>
<t tx="iggu.20191119114314.1">
# remove trailing whitespaces for every line in the current node's body
# command is bound to shortcut in the @keys section

CommandName = 'rstrip-node'

body = c.frame.body
cursor = body.widget.textCursor()
cp = cursor.position()  # remember position - cause updateBodyPane changes it

# FIXME: both algos are buggy! cursor is set to the prev pos aftewards but!
# since some spaces can be removed above the cursor - it will jump forward
# for the amount of removed spaces

if True:  # straightforward version
    b = c.undoer.beforeChangeNodeContents(p)
    content = "\n".join( (l.rstrip() for l in c.p.b.splitlines()) )
    c.p.b = content
    c.undoer.afterChangeNodeContents(p, command=CommandName, bunch=b)

else:  # sophisticated and cryptic version
    # rstrip all lines
    head, lines, tail, oldSel, oldYview = c.getBodyLines()  # lines above, under and below cursor
    rstrip_lines = lambda ll: "\n".join( (l.rstrip() for l in ll) )
    head = rstrip_lines(head.splitlines())
    lines = rstrip_lines(lines)
    tail = rstrip_lines(tail.splitlines())

    # set rstripped lines
    prefix, suffix = '\n' if head else '', '\n' if tail else ''
    c.updateBodyPane(head, prefix+lines+suffix, tail,
                     undoType=CommandName, oldSel=None, oldYview=oldYview)


body.wrapper.setSelectionRange(cp, cp)  # drop any selection and return cursor to where it was</t>
<t tx="iggu.20191119121604.1">@language python
</t>
<t tx="iggu.20191127153547.1">
@raw


body = """@language html

&lt;html&gt;
    &lt;head&gt;
        &lt;meta charset="utf-8"&gt;
        &lt;title&gt;&lt;/title&gt;

        &lt;style&gt;
            &lt;&lt; style &gt;&gt;
        &lt;/style&gt;

        &lt;script&gt;
            &lt;&lt; script :: head &gt;&gt;
        &lt;/script&gt;
    &lt;/head&gt;

    &lt;body&gt;
        &lt;&lt; body &gt;&gt;

        &lt;script&gt;
            &lt;&lt; script :: body &gt;&gt;
        &lt;/script&gt;
    &lt;/body&gt;
&lt;/html&gt;
"""

undoer = c.undoer
undoType = 'Create new HTML @clean file'
undoer.beforeChangeGroup(c.p, undoType)  # 1st arg - position to select after undo
bbbb = undoer.beforeInsertNode(c.p)

pRoot = c.p.insertAsNthChild(0)
pRoot.h = f'@clean .html'
pRoot.expand()

pScriptH = pRoot.insertAsLastChild()
pScriptH.h = "&lt;&lt; script :: head &gt;&gt;"
pScriptH.b = "@language javascript\n\n"

pScriptB = pRoot.insertAsLastChild()
pScriptB.h = "&lt;&lt; script :: body &gt;&gt;"
pScriptB.b = "@language javascript\n\n"

pStyle = pRoot.insertAsLastChild()
pStyle.h = "&lt;&lt; style &gt;&gt;"
pStyle.b = "@language css\n\n"

pHtml = pRoot.insertAsLastChild()
pHtml.h = "&lt;&lt; body &gt;&gt;"
pHtml.b = "@language html\n\n"

pRoot.b = body

c.setChanged(True)
c.selectPosition(pRoot)
c.redraw()

k = c.k
k.setLabelBlue('Filename: ')

def pRoot_set_filename(_):
    pRoot.h = f'@clean {k.arg}.html'
    k.clearState()
    k.resetLabel()
    k.showStateAndMode()
    undoer.afterInsertNode(pRoot, 'insert', bbbb)
    c.treeWantsFocus()

k.get1Arg(None, handler=pRoot_set_filename)
</t>
<t tx="iggu.20191204061052.1">@language python
</t>
<t tx="iggu.20191204061525.1"></t>
<t tx="iggu.20191205122008.1">https://github.com/leo-editor/leo-editor/issues/568
https://github.com/leo-editor/leo-editor/issues/1102

</t>
<t tx="iggu.20191205123014.1"># is critically outdated</t>
<t tx="iggu.20201107154858.1">https://github.com/leo-editor/leo-editor/issues/568
https://github.com/leo-editor/leo-editor/issues/1102
</t>
<t tx="iggu.20201219000309.1"></t>
<t tx="iggu.20201219000321.1"></t>
<t tx="iggu.20201225013248.1">
&lt;&lt; load and import &gt;&gt;
from commands import CmdWip

try:
    cmd = CmdWip(c.p)

    if cmd.push():
        g.es(f"&lt;{c.p.h}&gt;", "inserted to WIP")
    elif cmd.pop():
        g.es(f"&lt;{c.p.h}&gt;", "removed from WIP")
    else:
        g.es(f"&lt;{c.p.h}&gt;", "nothing to do in WIP command")

except Exception as e:
    import traceback
    traceback.print_exc()
    g.es(f"&lt;{c.p.h}&gt;:", str(e), color="red")
</t>
<t tx="iggu.20201225013248.2">
exec("\n".join(c.config.getData("import-and-init-leo-py-libs", strip_data=False)))
import_leo_user_libs("ltools", "commands", forceReload=True)
</t>
<t tx="iggu.20201225013435.1">
def __acquire_module(name, forceReload):
    import sys
    import os.path
    import importlib.util
    if (not forceReload and name in sys.modules):
        module = sys.modules[name]
    else:
        configLibPath = os.path.expanduser(c.config.getString('confg-lib-dir'))
        rootDir = configLibPath + "/"
        leostuffLibsDir = rootDir + name + ".py"
        spec = importlib.util.spec_from_file_location(name, leostuffLibsDir)
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
    return module


def import_leo_user_libs(*names, forceReload=False):
    try:
        iter(names)
    except TypeError:
        names = [names]
    for name in names:
        module = __acquire_module(name, forceReload)
        list(map(lambda k: setattr(module, k, globals().get(k, None)),
                 filter(lambda k: hasattr(module, k), ["c", "g"])))
        # [setattr(module, k, globals().get(k, None)) for k in ["c", "g"] if hasattr(module, k)]
</t>
<t tx="iggu.20201225013512.1">
&lt;&lt; load and import &gt;&gt;
from commands import CmdWip

try:
    cmd = CmdWip(c.p)

    if cmd.pop():
        g.es(f"&lt;{c.p.h}&gt;", "removed from WIP chapter")
    else:
        g.es(f"&lt;{c.p.h}&gt;", "not in WIP chapter")

except Exception as e:
    g.es(f"&lt;{c.p.h}&gt;:", str(e), color="red")
</t>
<t tx="iggu.20201225013523.1">
&lt;&lt; load and import &gt;&gt;
from commands import CmdWip

try:
    cmd = CmdWip(c.p)

    if cmd.push(undo=True, insertFirst=False, expand=True):
        g.es(f"&lt;{c.p.h}&gt;", "inserted to WIP chapter")
    else:
        g.es(f"&lt;{c.p.h}&gt;", "already in WIP chapter")

except Exception as e:
    g.es(f"&lt;{c.p.h}&gt;:", str(e), color="red")
</t>
<t tx="iggu.20220327131002.1">{
    "content": [
        "_leo_pane:outlineFrame",
        "_leo_pane:bodyFrame",
        {
            "content": [
                "_leo_tab:Find",
                "_leo_pane:logFrame"
            ],
            "orientation": 2,
            "sizes": [
                300,
                750
            ]
        }
    ],
    "orientation": 1,
    "sizes": [
        350,
        1200,
        350
    ]
}</t>
<t tx="iggu.20220405122317.1">
import os

olFile = os.path.realpath(c.fileName())
olDir = os.path.realpath(os.path.dirname(olFile))

g.es(c.fileName())
os.system("cd '" + olDir + "' &amp;&amp; (git gui || xterm -geom 400x120 -e gitui)")</t>
</tnodes>
</leo_file>
