
colors:
  body: none
  date: black
  tags: yellow
  title: cyan
default_hour: 9
default_minute: 0
editor: 'vim'
encrypt: false
highlight: true
indent_character: '|'
journals:
  lope:
    journal: ~/Documents/lope/journal.txt
    encrypt: false
linewrap: 79
tagsymbols: '#@'
template: false
timeformat: '%F %r'
version: v4.0.1
